"""Base declarative class for SQLAlchemy models."""
from app.db.base_class import Base

# Import models here so Alembic can discover them.
from app.models import (  # noqa: F401
    DiceConfig,
    DiceLog,
    FeatureConfig,
    FeatureSchedule,
    AppUiConfig,
    ExternalRankingData,
    ExternalRankingDailyDepositDelta,
    ExternalRankingRewardLog,
    GameTokenType,
    LotteryConfig,
    LotteryLog,
    LotteryPrize,
    RankingDaily,
    UserEventLog,
    RouletteConfig,
    RouletteLog,
    RouletteSegment,
    SeasonPassConfig,
    SeasonPassLevel,
    SeasonPassProgress,
    SeasonPassRewardLog,
    SeasonPassStampLog,
    TeamSeason,
    Team,
    TeamMember,
    TeamScore,
    TeamEventLog,
    UserLevelProgress,
    UserLevelRewardLog,
    UserXpEventLog,
    User,
    UserCashLedger,
    UserGameWallet,
    V2Survey,
    V2SurveyQuestion,
    V2SurveyOption,
    V2SurveyTriggerRule,
    V2SurveyResponse,
    V2SurveyResponseAnswer,
    UserActivity,
    UserActivityEvent,
    UserSegment,
    SegmentRule,
    VaultProgram,
    VaultStatus,
    VaultEarnEvent,
    TrialTokenBucket,
    TelegramLinkCode,
    Mission,
    UserMissionProgress,
    UserIdempotencyKey,
    OpsDailyLog,
    OpsLogEntry,
    OpsCampaign,
    OpsPlan,
    OpsPlanTask,
    OpsEvalMetric,
    OpsTargetList,
    OpsTargetMember,
    EventConfig,
    EventParticipationLog,
    VaultLedger,
)
from app.models.admin_user_profile import AdminUserProfile
from app.models.admin_message import AdminMessage, AdminMessageInbox
from app.models.user_history import UserIdentityHistory
from app.v2.models import (
    V2User, 
    V2UserDepositEvidence,
    V2UserAuthEvent,
    V2UserRefreshToken,
    V2GoldenInterventionLog,
    V2UserRetentionState,
    V2OpsExecutionResult,
    V2RetentionRoiLog,
    V2ServerConfig,
    V2ShopOrder,
    V2SegmentRule,
    V2UserSegment,
)
