[pytest]
testpaths = tests
pythonpath = .
addopts = -v -p no:asyncio
filterwarnings =
    ignore::pydantic.warnings.PydanticDeprecatedSince20
    ignore:Valid config keys have changed in V2:UserWarning
    ignore:Support for class-based `config` is deprecated:DeprecationWarning
