// SoT 20개 재화 목록
export const SOT_REWARD_TYPES = [
  { value: "ROULETTE_TICKET", label: "룰렛 티켓" },
  { value: "DICE_TICKET", label: "다이스 티켓" },
  { value: "LOTTERY_TICKET", label: "복권 티켓" },
  { value: "VAULT", label: "금고 포인트" },
  { value: "GOLD_KEY_TICKET", label: "골드 열쇠 티켓" },
  { value: "DIAMOND_TICKET", label: "다이아몬드 티켓" },
  { value: "GOLD_KEY_FRAGMENT", label: "골드 열쇠 조각" },
  { value: "DIAMOND_FRAGMENT", label: "다이아몬드 조각" },
  { value: "PUZZLE_C1", label: "퍼즐 조각 C1" },
  { value: "PUZZLE_C2", label: "퍼즐 조각 C2" },
  { value: "PUZZLE_J", label: "퍼즐 조각 J" },
  { value: "PUZZLE_M", label: "퍼즐 조각 M" },
  { value: "DIAMOND", label: "다이아몬드" },
  { value: "CHICKEN_GIFTICON_5000", label: "치킨 기프티콘 5천원" },
  { value: "CHICKEN_GIFTICON_10000", label: "치킨 기프티콘 1만원" },
  { value: "STARBUCKS_GIFTICON_2000", label: "스타벅스 기프티콘 2천원" },
  { value: "STARBUCKS_GIFTICON_10000", label: "스타벅스 기프티콘 1만원" },
  { value: "PIZZA_GIFTICON_5000", label: "피자 기프티콘 5천원" },
  { value: "PIZZA_GIFTICON_10000", label: "피자 기프티콘 1만원" },
  { value: "GOOGLE_GIFTICON_5000", label: "구글 기프트카드 5천원" },
  { value: "GOOGLE_GIFTICON_10000", label: "구글 기프트카드 1만원" },
] as const;
