"""add admin audit log

Revision ID: db42510e351c
Revises: 20251225_0005
Create Date: 2025-12-25 16:26:04.359180+09:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'db42510e351c'
down_revision = '20251225_0005'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('target_type', sa.String(length=50), nullable=True),
    sa.Column('target_id', sa.String(length=100), nullable=True),
    sa.Column('before_json', sa.JSON().with_variant(mysql.JSON(), 'mysql'), nullable=True),
    sa.Column('after_json', sa.JSON().with_variant(mysql.JSON(), 'mysql'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_audit_log_admin_id'), 'admin_audit_log', ['admin_id'], unique=False)
    op.create_index(op.f('ix_admin_audit_log_id'), 'admin_audit_log', ['id'], unique=False)
    op.alter_column('app_ui_config', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('app_ui_config', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('external_ranking_data', 'deposit_remainder',
               existing_type=mysql.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('new_member_dice_eligibility', 'is_eligible',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=None,
               existing_nullable=False)
    op.alter_column('new_member_dice_eligibility', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('new_member_dice_eligibility', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=None,
               existing_nullable=False)
    op.create_index(op.f('ix_new_member_dice_eligibility_id'), 'new_member_dice_eligibility', ['id'], unique=False)
    op.alter_column('new_member_dice_log', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=None,
               existing_nullable=False)
    op.create_index(op.f('ix_new_member_dice_log_id'), 'new_member_dice_log', ['id'], unique=False)
    op.alter_column('season_pass_config', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('season_pass_config', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('season_pass_level', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('season_pass_level', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('season_pass_progress', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('season_pass_progress', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('season_pass_reward_log', 'claimed_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('season_pass_reward_log', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('season_pass_stamp_log', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('segment_rule', 'priority',
               existing_type=mysql.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('segment_rule', 'enabled',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=None,
               existing_nullable=False)
    op.alter_column('segment_rule', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('segment_rule', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('survey', 'status',
               existing_type=mysql.ENUM('DRAFT', 'ACTIVE', 'PAUSED', 'ARCHIVED', charset='utf8mb4', collation='utf8mb4_unicode_ci'),
               server_default=None,
               existing_nullable=False)
    op.alter_column('survey', 'channel',
               existing_type=mysql.ENUM('GLOBAL', 'SEASON_PASS', 'ROULETTE', 'DICE', 'LOTTERY', 'TEAM_BATTLE', charset='utf8mb4', collation='utf8mb4_unicode_ci'),
               server_default=None,
               existing_nullable=False)
    op.alter_column('survey', 'auto_launch',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=None,
               existing_nullable=False)
    op.alter_column('survey', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('survey', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('survey_option', 'weight',
               existing_type=mysql.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('survey_option', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('survey_option', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('survey_question', 'is_required',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=None,
               existing_nullable=False)
    op.alter_column('survey_question', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('survey_question', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('survey_response', 'status',
               existing_type=mysql.ENUM('PENDING', 'IN_PROGRESS', 'COMPLETED', 'DROPPED', 'EXPIRED', charset='utf8mb4', collation='utf8mb4_unicode_ci'),
               server_default=None,
               existing_nullable=False)
    op.alter_column('survey_response', 'reward_status',
               existing_type=mysql.ENUM('NONE', 'SCHEDULED', 'GRANTED', 'FAILED', charset='utf8mb4', collation='utf8mb4_unicode_ci'),
               server_default=None,
               existing_nullable=False)
    op.alter_column('survey_response', 'last_activity_at',
               existing_type=mysql.DATETIME(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('survey_response', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('survey_response', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=None,
               existing_nullable=False)
    op.drop_index('idx_survey_response_survey', table_name='survey_response')
    op.drop_index('idx_survey_response_user', table_name='survey_response')
    op.alter_column('survey_response_answer', 'answered_at',
               existing_type=mysql.DATETIME(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('survey_trigger_rule', 'priority',
               existing_type=mysql.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('survey_trigger_rule', 'cooldown_hours',
               existing_type=mysql.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('survey_trigger_rule', 'max_per_user',
               existing_type=mysql.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('survey_trigger_rule', 'is_active',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=None,
               existing_nullable=False)
    op.alter_column('survey_trigger_rule', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('survey_trigger_rule', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=None,
               existing_nullable=False)
    op.drop_index('idx_survey_trigger_active', table_name='survey_trigger_rule')
    op.alter_column('team', 'is_active',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=None,
               existing_nullable=False)
    op.alter_column('team', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('team', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=None,
               existing_nullable=False)
    op.create_index(op.f('ix_team_id'), 'team', ['id'], unique=False)
    op.alter_column('team_event_log', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('team_member', 'role',
               existing_type=mysql.VARCHAR(length=10),
               server_default=None,
               existing_nullable=False)
    op.alter_column('team_member', 'joined_at',
               existing_type=mysql.DATETIME(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('team_score', 'points',
               existing_type=mysql.BIGINT(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('team_score', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('team_season', 'is_active',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=None,
               existing_nullable=False)
    op.alter_column('team_season', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('team_season', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=None,
               existing_nullable=False)
    op.create_index(op.f('ix_team_season_id'), 'team_season', ['id'], unique=False)
    op.alter_column('trial_token_bucket', 'balance',
               existing_type=mysql.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('trial_token_bucket', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=None,
               existing_nullable=False)
    op.create_index(op.f('ix_trial_token_bucket_id'), 'trial_token_bucket', ['id'], unique=False)
    op.alter_column('user_activity', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('user_activity', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('user_activity_event', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('user_cash_ledger', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=None,
               existing_nullable=False)
    op.drop_index('ix_user_cash_ledger_user_created_at', table_name='user_cash_ledger')
    op.alter_column('user_level_progress', 'level',
               existing_type=mysql.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('user_level_progress', 'xp',
               existing_type=mysql.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('user_level_progress', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('user_level_reward_log', 'id',
               existing_type=mysql.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('user_level_reward_log', 'auto_granted',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=None,
               existing_nullable=False)
    op.alter_column('user_level_reward_log', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=None,
               existing_nullable=False)
    op.drop_index('idx_ulrl_user_created', table_name='user_level_reward_log')
    op.create_index(op.f('ix_user_level_reward_log_id'), 'user_level_reward_log', ['id'], unique=False)
    op.alter_column('user_segment', 'segment',
               existing_type=mysql.VARCHAR(length=50),
               server_default=None,
               existing_nullable=False)
    op.alter_column('user_segment', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('user_xp_event_log', 'id',
               existing_type=mysql.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('user_xp_event_log', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=None,
               existing_nullable=False)
    op.drop_index('idx_uxel_user_created', table_name='user_xp_event_log')
    op.create_index(op.f('ix_user_xp_event_log_id'), 'user_xp_event_log', ['id'], unique=False)
    op.create_unique_constraint(None, 'user_xp_event_log', ['id'])
    op.alter_column('vault_earn_event', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=None,
               existing_nullable=False)
    op.create_index(op.f('ix_vault_earn_event_id'), 'vault_earn_event', ['id'], unique=False)
    op.alter_column('vault_program', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('vault_program', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('vault_status', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('vault_status', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=None,
               existing_nullable=False)
    op.drop_index('uq_vault_status_user_program', table_name='vault_status')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('uq_vault_status_user_program', 'vault_status', ['user_id', 'program_id'], unique=True)
    op.alter_column('vault_status', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.alter_column('vault_status', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.alter_column('vault_program', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.alter_column('vault_program', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.drop_index(op.f('ix_vault_earn_event_id'), table_name='vault_earn_event')
    op.alter_column('vault_earn_event', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.drop_constraint(None, 'user_xp_event_log', type_='unique')
    op.drop_index(op.f('ix_user_xp_event_log_id'), table_name='user_xp_event_log')
    op.create_index('idx_uxel_user_created', 'user_xp_event_log', ['user_id', 'created_at'], unique=False)
    op.alter_column('user_xp_event_log', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.alter_column('user_xp_event_log', 'id',
               existing_type=sa.Integer(),
               type_=mysql.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('user_segment', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.alter_column('user_segment', 'segment',
               existing_type=mysql.VARCHAR(length=50),
               server_default=sa.text("'NEW'"),
               existing_nullable=False)
    op.drop_index(op.f('ix_user_level_reward_log_id'), table_name='user_level_reward_log')
    op.create_index('idx_ulrl_user_created', 'user_level_reward_log', ['user_id', 'created_at'], unique=False)
    op.alter_column('user_level_reward_log', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.alter_column('user_level_reward_log', 'auto_granted',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text("'0'"),
               existing_nullable=False)
    op.alter_column('user_level_reward_log', 'id',
               existing_type=sa.Integer(),
               type_=mysql.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('user_level_progress', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.alter_column('user_level_progress', 'xp',
               existing_type=mysql.INTEGER(),
               server_default=sa.text("'0'"),
               existing_nullable=False)
    op.alter_column('user_level_progress', 'level',
               existing_type=mysql.INTEGER(),
               server_default=sa.text("'1'"),
               existing_nullable=False)
    op.create_index('ix_user_cash_ledger_user_created_at', 'user_cash_ledger', ['user_id', 'created_at'], unique=False)
    op.alter_column('user_cash_ledger', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.alter_column('user_activity_event', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.alter_column('user_activity', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.alter_column('user_activity', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.drop_index(op.f('ix_trial_token_bucket_id'), table_name='trial_token_bucket')
    op.alter_column('trial_token_bucket', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.alter_column('trial_token_bucket', 'balance',
               existing_type=mysql.INTEGER(),
               server_default=sa.text("'0'"),
               existing_nullable=False)
    op.drop_index(op.f('ix_team_season_id'), table_name='team_season')
    op.alter_column('team_season', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.alter_column('team_season', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.alter_column('team_season', 'is_active',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text("'0'"),
               existing_nullable=False)
    op.alter_column('team_score', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.alter_column('team_score', 'points',
               existing_type=mysql.BIGINT(),
               server_default=sa.text("'0'"),
               existing_nullable=False)
    op.alter_column('team_member', 'joined_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.alter_column('team_member', 'role',
               existing_type=mysql.VARCHAR(length=10),
               server_default=sa.text("'member'"),
               existing_nullable=False)
    op.alter_column('team_event_log', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.drop_index(op.f('ix_team_id'), table_name='team')
    op.alter_column('team', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.alter_column('team', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.alter_column('team', 'is_active',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text("'1'"),
               existing_nullable=False)
    op.create_index('idx_survey_trigger_active', 'survey_trigger_rule', ['is_active', 'priority'], unique=False)
    op.alter_column('survey_trigger_rule', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.alter_column('survey_trigger_rule', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.alter_column('survey_trigger_rule', 'is_active',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text("'1'"),
               existing_nullable=False)
    op.alter_column('survey_trigger_rule', 'max_per_user',
               existing_type=mysql.INTEGER(),
               server_default=sa.text("'1'"),
               existing_nullable=False)
    op.alter_column('survey_trigger_rule', 'cooldown_hours',
               existing_type=mysql.INTEGER(),
               server_default=sa.text("'24'"),
               existing_nullable=False)
    op.alter_column('survey_trigger_rule', 'priority',
               existing_type=mysql.INTEGER(),
               server_default=sa.text("'100'"),
               existing_nullable=False)
    op.alter_column('survey_response_answer', 'answered_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.create_index('idx_survey_response_user', 'survey_response', ['user_id', 'status'], unique=False)
    op.create_index('idx_survey_response_survey', 'survey_response', ['survey_id', 'status'], unique=False)
    op.alter_column('survey_response', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.alter_column('survey_response', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.alter_column('survey_response', 'last_activity_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.alter_column('survey_response', 'reward_status',
               existing_type=mysql.ENUM('NONE', 'SCHEDULED', 'GRANTED', 'FAILED', charset='utf8mb4', collation='utf8mb4_unicode_ci'),
               server_default=sa.text("'NONE'"),
               existing_nullable=False)
    op.alter_column('survey_response', 'status',
               existing_type=mysql.ENUM('PENDING', 'IN_PROGRESS', 'COMPLETED', 'DROPPED', 'EXPIRED', charset='utf8mb4', collation='utf8mb4_unicode_ci'),
               server_default=sa.text("'PENDING'"),
               existing_nullable=False)
    op.alter_column('survey_question', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.alter_column('survey_question', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.alter_column('survey_question', 'is_required',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text("'1'"),
               existing_nullable=False)
    op.alter_column('survey_option', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.alter_column('survey_option', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.alter_column('survey_option', 'weight',
               existing_type=mysql.INTEGER(),
               server_default=sa.text("'1'"),
               existing_nullable=False)
    op.alter_column('survey', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.alter_column('survey', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.alter_column('survey', 'auto_launch',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text("'0'"),
               existing_nullable=False)
    op.alter_column('survey', 'channel',
               existing_type=mysql.ENUM('GLOBAL', 'SEASON_PASS', 'ROULETTE', 'DICE', 'LOTTERY', 'TEAM_BATTLE', charset='utf8mb4', collation='utf8mb4_unicode_ci'),
               server_default=sa.text("'GLOBAL'"),
               existing_nullable=False)
    op.alter_column('survey', 'status',
               existing_type=mysql.ENUM('DRAFT', 'ACTIVE', 'PAUSED', 'ARCHIVED', charset='utf8mb4', collation='utf8mb4_unicode_ci'),
               server_default=sa.text("'DRAFT'"),
               existing_nullable=False)
    op.alter_column('segment_rule', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.alter_column('segment_rule', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.alter_column('segment_rule', 'enabled',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text("'1'"),
               existing_nullable=False)
    op.alter_column('segment_rule', 'priority',
               existing_type=mysql.INTEGER(),
               server_default=sa.text("'100'"),
               existing_nullable=False)
    op.alter_column('season_pass_stamp_log', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.alter_column('season_pass_reward_log', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.alter_column('season_pass_reward_log', 'claimed_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.alter_column('season_pass_progress', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.alter_column('season_pass_progress', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.alter_column('season_pass_level', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.alter_column('season_pass_level', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.alter_column('season_pass_config', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.alter_column('season_pass_config', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.drop_index(op.f('ix_new_member_dice_log_id'), table_name='new_member_dice_log')
    op.alter_column('new_member_dice_log', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.drop_index(op.f('ix_new_member_dice_eligibility_id'), table_name='new_member_dice_eligibility')
    op.alter_column('new_member_dice_eligibility', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.alter_column('new_member_dice_eligibility', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.alter_column('new_member_dice_eligibility', 'is_eligible',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text("'1'"),
               existing_nullable=False)
    op.alter_column('external_ranking_data', 'deposit_remainder',
               existing_type=mysql.INTEGER(),
               server_default=sa.text("'0'"),
               existing_nullable=False)
    op.alter_column('app_ui_config', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.alter_column('app_ui_config', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.drop_index(op.f('ix_admin_audit_log_id'), table_name='admin_audit_log')
    op.drop_index(op.f('ix_admin_audit_log_admin_id'), table_name='admin_audit_log')
    op.drop_table('admin_audit_log')
    # ### end Alembic commands ###
