"""refactor_survey_fk_to_v2user

Revision ID: 18e1aca5529f
Revises: 20260204_0200_add_segment_check_constraint
Create Date: 2026-02-04 15:00:42.487146+09:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '18e1aca5529f'
down_revision = '20260204_0200_add_segment_check_constraint'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('admin_message_inbox_fk_v2_user', 'admin_message_inbox', type_='foreignkey')
    op.create_foreign_key(None, 'admin_message_inbox', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('dice_log_fk_v2_user', 'dice_log', type_='foreignkey')
    op.create_foreign_key(None, 'dice_log', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('event_participation_log_fk_v2_user', 'event_participation_log', type_='foreignkey')
    op.create_foreign_key(None, 'event_participation_log', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('external_ranking_daily_deposit_delta_fk_v2_user', 'external_ranking_daily_deposit_delta', type_='foreignkey')
    op.create_foreign_key(None, 'external_ranking_daily_deposit_delta', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'external_ranking_data', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('external_ranking_reward_log_fk_v2_user', 'external_ranking_reward_log', type_='foreignkey')
    op.create_foreign_key(None, 'external_ranking_reward_log', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('hq_daily_deposit_log', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=None,
               existing_nullable=False)
    op.drop_index('dedup_key', table_name='hq_daily_deposit_log')
    op.drop_index('ix_hq_daily_deposit_log_dedup_key', table_name='hq_daily_deposit_log')
    op.create_index(op.f('ix_hq_daily_deposit_log_dedup_key'), 'hq_daily_deposit_log', ['dedup_key'], unique=True)
    op.alter_column('hq_prospective_user', 'ignored',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=None,
               existing_nullable=True)
    op.create_index(op.f('ix_hq_prospective_user_id'), 'hq_prospective_user', ['id'], unique=False)
    op.drop_constraint('fk_hq_prospective_user_linked_user_id', 'hq_prospective_user', type_='foreignkey')
    op.create_foreign_key(None, 'hq_prospective_user', 'v2_user', ['linked_user_id'], ['id'])
    op.drop_constraint('lottery_log_fk_v2_user', 'lottery_log', type_='foreignkey')
    op.create_foreign_key(None, 'lottery_log', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('ops_target_member_fk_v2_user', 'ops_target_member', type_='foreignkey')
    op.create_foreign_key(None, 'ops_target_member', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('ranking_daily_fk_v2_user', 'ranking_daily', type_='foreignkey')
    op.create_foreign_key(None, 'ranking_daily', 'user', ['user_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint('retention_roi_log_fk_v2_user', 'retention_roi_log', type_='foreignkey')
    op.create_foreign_key(None, 'retention_roi_log', 'user', ['user_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint('roulette_log_fk_v2_user', 'roulette_log', type_='foreignkey')
    op.create_foreign_key(None, 'roulette_log', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('season_pass_config', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('season_pass_config', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('season_pass_level', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('season_pass_level', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('season_pass_progress', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('season_pass_progress', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.drop_constraint('season_pass_progress_fk_v2_user', 'season_pass_progress', type_='foreignkey')
    op.create_foreign_key(None, 'season_pass_progress', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('season_pass_reward_log', 'claimed_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('season_pass_reward_log', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.drop_constraint('season_pass_reward_log_fk_v2_user', 'season_pass_reward_log', type_='foreignkey')
    op.create_foreign_key(None, 'season_pass_reward_log', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('season_pass_stamp_log', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.drop_constraint('season_pass_stamp_log_fk_v2_user', 'season_pass_stamp_log', type_='foreignkey')
    op.create_foreign_key(None, 'season_pass_stamp_log', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'survey', 'v2_user', ['created_by'], ['id'], ondelete='SET NULL')
    op.drop_constraint('team_event_log_fk_v2_user', 'team_event_log', type_='foreignkey')
    op.create_foreign_key(None, 'team_event_log', 'user', ['user_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint('team_member_fk_v2_user', 'team_member', type_='foreignkey')
    op.create_foreign_key(None, 'team_member', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('telegram_link_code_fk_v2_user', 'telegram_link_code', type_='foreignkey')
    op.create_foreign_key(None, 'telegram_link_code', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('trial_token_bucket_fk_v2_user', 'trial_token_bucket', type_='foreignkey')
    op.create_foreign_key(None, 'trial_token_bucket', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'user_activity', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('user_activity_event_fk_v2_user', 'user_activity_event', type_='foreignkey')
    op.create_foreign_key(None, 'user_activity_event', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('user_cash_ledger_fk_v2_user', 'user_cash_ledger', type_='foreignkey')
    op.create_foreign_key(None, 'user_cash_ledger', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('user_event_log_fk_v2_user', 'user_event_log', type_='foreignkey')
    op.create_foreign_key(None, 'user_event_log', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('user_idempotency_key_fk_v2_user', 'user_idempotency_key', type_='foreignkey')
    op.create_foreign_key(None, 'user_idempotency_key', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('user_identity_history_fk_v2_user', 'user_identity_history', type_='foreignkey')
    op.create_foreign_key(None, 'user_identity_history', 'user', ['user_id'], ['id'])
    op.drop_constraint('user_level_progress_fk_v2_user', 'user_level_progress', type_='foreignkey')
    op.create_foreign_key(None, 'user_level_progress', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('user_level_reward_log_fk_v2_user', 'user_level_reward_log', type_='foreignkey')
    op.create_foreign_key(None, 'user_level_reward_log', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'user_mission_progress', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('user_retention_state_fk_v2_user', 'user_retention_state', type_='foreignkey')
    op.create_foreign_key(None, 'user_retention_state', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('user_segment_fk_v2_user', 'user_segment', type_='foreignkey')
    op.create_foreign_key(None, 'user_segment', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('user_streak_fk_v2_user', 'user_streak', type_='foreignkey')
    op.create_foreign_key(None, 'user_streak', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('user_xp_event_log_fk_v2_user', 'user_xp_event_log', type_='foreignkey')
    op.create_foreign_key(None, 'user_xp_event_log', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('v2_dice_config', 'golden_hour_start_time',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=8),
               server_default=None,
               existing_nullable=False)
    op.alter_column('v2_dice_config', 'golden_hour_end_time',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=8),
               server_default=None,
               existing_nullable=False)
    op.alter_column('v2_dice_log', 'user_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.drop_constraint('fk_v2_dice_log_user_id', 'v2_dice_log', type_='foreignkey')
    op.alter_column('v2_external_deposit_unmatched', 'source',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               server_default=None,
               existing_nullable=False)
    op.alter_column('v2_external_deposit_unmatched', 'prev_total',
               existing_type=mysql.BIGINT(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('v2_external_deposit_unmatched', 'delta',
               existing_type=mysql.BIGINT(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('v2_external_deposit_unmatched', 'status',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               server_default=None,
               existing_nullable=False)
    op.alter_column('v2_external_deposit_unmatched', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('v2_external_deposit_unmatched', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=None,
               existing_nullable=False)
    op.create_index(op.f('ix_v2_external_deposit_unmatched_kst_date'), 'v2_external_deposit_unmatched', ['kst_date'], unique=False)
    op.create_index(op.f('ix_v2_external_deposit_unmatched_matched_user_id'), 'v2_external_deposit_unmatched', ['matched_user_id'], unique=False)
    op.alter_column('v2_game_log', 'bet_amount',
               existing_type=mysql.BIGINT(),
               server_default=None,
               existing_comment='배팅 금액 (원)',
               existing_nullable=False)
    op.alter_column('v2_game_log', 'payout_amount',
               existing_type=mysql.BIGINT(),
               server_default=None,
               existing_comment='지급 금액 (원)',
               existing_nullable=False)
    op.alter_column('v2_game_log', 'balance_after',
               existing_type=mysql.BIGINT(),
               server_default=None,
               existing_comment='게임 후 잔액 (원)',
               existing_nullable=False)
    op.alter_column('v2_game_log', 'imported_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_comment='시스템 반입 시각',
               existing_nullable=False)
    op.alter_column('v2_lottery_log', 'user_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.drop_constraint('fk_v2_lottery_log_user_id', 'v2_lottery_log', type_='foreignkey')
    op.create_index('idx_v2_retention_roi_log_event_created', 'v2_retention_roi_log', ['event_type', 'created_at'], unique=False)
    op.drop_constraint('v2_retention_roi_log_fk_v2_user', 'v2_retention_roi_log', type_='foreignkey')
    op.create_foreign_key(None, 'v2_retention_roi_log', 'v2_user', ['user_id'], ['id'], ondelete='SET NULL')
    op.alter_column('v2_roulette_log', 'user_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.drop_constraint('fk_v2_roulette_log_user_id', 'v2_roulette_log', type_='foreignkey')
    op.alter_column('v2_shop_order', 'user_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.drop_constraint('fk_v2_shop_order_user_id', 'v2_shop_order', type_='foreignkey')
    op.alter_column('v2_user', 'vault_available_balance',
               existing_type=mysql.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('v2_user', 'level',
               existing_type=mysql.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('v2_user', 'vault_spent_total',
               existing_type=mysql.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('v2_user', 'vault_spent_today',
               existing_type=mysql.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('v2_user', 'total_charge_amount',
               existing_type=mysql.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('v2_user', 'baseline_charge_amount',
               existing_type=mysql.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('v2_user', 'play_streak',
               existing_type=mysql.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('v2_user', 'status',
               existing_type=mysql.ENUM('ACTIVE', 'INACTIVE', 'SUSPENDED', 'ADMIN', collation='utf8mb4_unicode_ci'),
               server_default=None,
               existing_nullable=False)
    op.alter_column('v2_user', 'role',
               existing_type=mysql.ENUM('USER', 'ADMIN', 'SUPER_ADMIN', collation='utf8mb4_unicode_ci'),
               server_default=None,
               existing_nullable=False)
    op.alter_column('v2_user_segment', 'total_margin',
               existing_type=mysql.BIGINT(),
               server_default=None,
               existing_comment='총 운영 마진 (충전 - 환전)',
               existing_nullable=True)
    op.alter_column('v2_user_segment', 'total_charge',
               existing_type=mysql.BIGINT(),
               server_default=None,
               existing_comment='누적 충전 금액',
               existing_nullable=True)
    op.alter_column('v2_user_segment', 'inactive_days',
               existing_type=mysql.INTEGER(),
               server_default=None,
               existing_comment='미접속 경과일',
               existing_nullable=True)
    op.alter_column('v2_user_segment', 'is_synced_from_hq',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=None,
               existing_comment='HQ CSV에서 동기화 여부',
               existing_nullable=False)
    op.drop_constraint('vault_earn_event_fk_v2_user', 'vault_earn_event', type_='foreignkey')
    op.create_foreign_key(None, 'vault_earn_event', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('vault_ledger_fk_v2_user', 'vault_ledger', type_='foreignkey')
    op.create_foreign_key(None, 'vault_ledger', 'user', ['user_id'], ['id'])
    op.drop_constraint('vault_status_fk_v2_user', 'vault_status', type_='foreignkey')
    op.create_foreign_key(None, 'vault_status', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('vault_withdrawal_request_fk_v2_user', 'vault_withdrawal_request', type_='foreignkey')
    op.create_foreign_key(None, 'vault_withdrawal_request', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vault_withdrawal_request', type_='foreignkey')
    op.create_foreign_key('vault_withdrawal_request_fk_v2_user', 'vault_withdrawal_request', 'v2_user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'vault_status', type_='foreignkey')
    op.create_foreign_key('vault_status_fk_v2_user', 'vault_status', 'v2_user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'vault_ledger', type_='foreignkey')
    op.create_foreign_key('vault_ledger_fk_v2_user', 'vault_ledger', 'v2_user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'vault_earn_event', type_='foreignkey')
    op.create_foreign_key('vault_earn_event_fk_v2_user', 'vault_earn_event', 'v2_user', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('v2_user_segment', 'is_synced_from_hq',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text("'0'"),
               existing_comment='HQ CSV에서 동기화 여부',
               existing_nullable=False)
    op.alter_column('v2_user_segment', 'inactive_days',
               existing_type=mysql.INTEGER(),
               server_default=sa.text("'0'"),
               existing_comment='미접속 경과일',
               existing_nullable=True)
    op.alter_column('v2_user_segment', 'total_charge',
               existing_type=mysql.BIGINT(),
               server_default=sa.text("'0'"),
               existing_comment='누적 충전 금액',
               existing_nullable=True)
    op.alter_column('v2_user_segment', 'total_margin',
               existing_type=mysql.BIGINT(),
               server_default=sa.text("'0'"),
               existing_comment='총 운영 마진 (충전 - 환전)',
               existing_nullable=True)
    op.alter_column('v2_user', 'role',
               existing_type=mysql.ENUM('USER', 'ADMIN', 'SUPER_ADMIN', collation='utf8mb4_unicode_ci'),
               server_default=sa.text("'USER'"),
               existing_nullable=False)
    op.alter_column('v2_user', 'status',
               existing_type=mysql.ENUM('ACTIVE', 'INACTIVE', 'SUSPENDED', 'ADMIN', collation='utf8mb4_unicode_ci'),
               server_default=sa.text("'ACTIVE'"),
               existing_nullable=False)
    op.alter_column('v2_user', 'play_streak',
               existing_type=mysql.INTEGER(),
               server_default=sa.text("'0'"),
               existing_nullable=False)
    op.alter_column('v2_user', 'baseline_charge_amount',
               existing_type=mysql.INTEGER(),
               server_default=sa.text("'0'"),
               existing_nullable=False)
    op.alter_column('v2_user', 'total_charge_amount',
               existing_type=mysql.INTEGER(),
               server_default=sa.text("'0'"),
               existing_nullable=False)
    op.alter_column('v2_user', 'vault_spent_today',
               existing_type=mysql.INTEGER(),
               server_default=sa.text("'0'"),
               existing_nullable=False)
    op.alter_column('v2_user', 'vault_spent_total',
               existing_type=mysql.INTEGER(),
               server_default=sa.text("'0'"),
               existing_nullable=False)
    op.alter_column('v2_user', 'level',
               existing_type=mysql.INTEGER(),
               server_default=sa.text("'1'"),
               existing_nullable=False)
    op.alter_column('v2_user', 'vault_available_balance',
               existing_type=mysql.INTEGER(),
               server_default=sa.text("'0'"),
               existing_nullable=False)
    op.create_foreign_key('fk_v2_shop_order_user_id', 'v2_shop_order', 'v2_user', ['user_id'], ['id'], ondelete='SET NULL')
    op.alter_column('v2_shop_order', 'user_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.create_foreign_key('fk_v2_roulette_log_user_id', 'v2_roulette_log', 'v2_user', ['user_id'], ['id'], ondelete='SET NULL')
    op.alter_column('v2_roulette_log', 'user_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'v2_retention_roi_log', type_='foreignkey')
    op.create_foreign_key('v2_retention_roi_log_fk_v2_user', 'v2_retention_roi_log', 'v2_user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index('idx_v2_retention_roi_log_event_created', table_name='v2_retention_roi_log')
    op.create_foreign_key('fk_v2_lottery_log_user_id', 'v2_lottery_log', 'v2_user', ['user_id'], ['id'], ondelete='SET NULL')
    op.alter_column('v2_lottery_log', 'user_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('v2_game_log', 'imported_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_comment='시스템 반입 시각',
               existing_nullable=False)
    op.alter_column('v2_game_log', 'balance_after',
               existing_type=mysql.BIGINT(),
               server_default=sa.text("'0'"),
               existing_comment='게임 후 잔액 (원)',
               existing_nullable=False)
    op.alter_column('v2_game_log', 'payout_amount',
               existing_type=mysql.BIGINT(),
               server_default=sa.text("'0'"),
               existing_comment='지급 금액 (원)',
               existing_nullable=False)
    op.alter_column('v2_game_log', 'bet_amount',
               existing_type=mysql.BIGINT(),
               server_default=sa.text("'0'"),
               existing_comment='배팅 금액 (원)',
               existing_nullable=False)
    op.drop_index(op.f('ix_v2_external_deposit_unmatched_matched_user_id'), table_name='v2_external_deposit_unmatched')
    op.drop_index(op.f('ix_v2_external_deposit_unmatched_kst_date'), table_name='v2_external_deposit_unmatched')
    op.alter_column('v2_external_deposit_unmatched', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('(now())'),
               existing_nullable=False)
    op.alter_column('v2_external_deposit_unmatched', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('(now())'),
               existing_nullable=False)
    op.alter_column('v2_external_deposit_unmatched', 'status',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               server_default=sa.text("'UNMATCHED'"),
               existing_nullable=False)
    op.alter_column('v2_external_deposit_unmatched', 'delta',
               existing_type=mysql.BIGINT(),
               server_default=sa.text("'0'"),
               existing_nullable=False)
    op.alter_column('v2_external_deposit_unmatched', 'prev_total',
               existing_type=mysql.BIGINT(),
               server_default=sa.text("'0'"),
               existing_nullable=False)
    op.alter_column('v2_external_deposit_unmatched', 'source',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               server_default=sa.text("'HQ_MARGIN'"),
               existing_nullable=False)
    op.create_foreign_key('fk_v2_dice_log_user_id', 'v2_dice_log', 'v2_user', ['user_id'], ['id'], ondelete='SET NULL')
    op.alter_column('v2_dice_log', 'user_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('v2_dice_config', 'golden_hour_end_time',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=8),
               server_default=sa.text("'22:30:00'"),
               existing_nullable=False)
    op.alter_column('v2_dice_config', 'golden_hour_start_time',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=8),
               server_default=sa.text("'21:30:00'"),
               existing_nullable=False)
    op.drop_constraint(None, 'user_xp_event_log', type_='foreignkey')
    op.create_foreign_key('user_xp_event_log_fk_v2_user', 'user_xp_event_log', 'v2_user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'user_streak', type_='foreignkey')
    op.create_foreign_key('user_streak_fk_v2_user', 'user_streak', 'v2_user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'user_segment', type_='foreignkey')
    op.create_foreign_key('user_segment_fk_v2_user', 'user_segment', 'v2_user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'user_retention_state', type_='foreignkey')
    op.create_foreign_key('user_retention_state_fk_v2_user', 'user_retention_state', 'v2_user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'user_mission_progress', type_='foreignkey')
    op.drop_constraint(None, 'user_level_reward_log', type_='foreignkey')
    op.create_foreign_key('user_level_reward_log_fk_v2_user', 'user_level_reward_log', 'v2_user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'user_level_progress', type_='foreignkey')
    op.create_foreign_key('user_level_progress_fk_v2_user', 'user_level_progress', 'v2_user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'user_identity_history', type_='foreignkey')
    op.create_foreign_key('user_identity_history_fk_v2_user', 'user_identity_history', 'v2_user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'user_idempotency_key', type_='foreignkey')
    op.create_foreign_key('user_idempotency_key_fk_v2_user', 'user_idempotency_key', 'v2_user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'user_event_log', type_='foreignkey')
    op.create_foreign_key('user_event_log_fk_v2_user', 'user_event_log', 'v2_user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'user_cash_ledger', type_='foreignkey')
    op.create_foreign_key('user_cash_ledger_fk_v2_user', 'user_cash_ledger', 'v2_user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'user_activity_event', type_='foreignkey')
    op.create_foreign_key('user_activity_event_fk_v2_user', 'user_activity_event', 'v2_user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'user_activity', type_='foreignkey')
    op.drop_constraint(None, 'trial_token_bucket', type_='foreignkey')
    op.create_foreign_key('trial_token_bucket_fk_v2_user', 'trial_token_bucket', 'v2_user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'telegram_link_code', type_='foreignkey')
    op.create_foreign_key('telegram_link_code_fk_v2_user', 'telegram_link_code', 'v2_user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'team_member', type_='foreignkey')
    op.create_foreign_key('team_member_fk_v2_user', 'team_member', 'v2_user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'team_event_log', type_='foreignkey')
    op.create_foreign_key('team_event_log_fk_v2_user', 'team_event_log', 'v2_user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'survey', type_='foreignkey')
    op.drop_constraint(None, 'season_pass_stamp_log', type_='foreignkey')
    op.create_foreign_key('season_pass_stamp_log_fk_v2_user', 'season_pass_stamp_log', 'v2_user', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('season_pass_stamp_log', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.drop_constraint(None, 'season_pass_reward_log', type_='foreignkey')
    op.create_foreign_key('season_pass_reward_log_fk_v2_user', 'season_pass_reward_log', 'v2_user', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('season_pass_reward_log', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.alter_column('season_pass_reward_log', 'claimed_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.drop_constraint(None, 'season_pass_progress', type_='foreignkey')
    op.create_foreign_key('season_pass_progress_fk_v2_user', 'season_pass_progress', 'v2_user', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('season_pass_progress', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.alter_column('season_pass_progress', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.alter_column('season_pass_level', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.alter_column('season_pass_level', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.alter_column('season_pass_config', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.alter_column('season_pass_config', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.drop_constraint(None, 'roulette_log', type_='foreignkey')
    op.create_foreign_key('roulette_log_fk_v2_user', 'roulette_log', 'v2_user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'retention_roi_log', type_='foreignkey')
    op.create_foreign_key('retention_roi_log_fk_v2_user', 'retention_roi_log', 'v2_user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'ranking_daily', type_='foreignkey')
    op.create_foreign_key('ranking_daily_fk_v2_user', 'ranking_daily', 'v2_user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'ops_target_member', type_='foreignkey')
    op.create_foreign_key('ops_target_member_fk_v2_user', 'ops_target_member', 'v2_user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'lottery_log', type_='foreignkey')
    op.create_foreign_key('lottery_log_fk_v2_user', 'lottery_log', 'v2_user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'hq_prospective_user', type_='foreignkey')
    op.create_foreign_key('fk_hq_prospective_user_linked_user_id', 'hq_prospective_user', 'v2_user', ['linked_user_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_hq_prospective_user_id'), table_name='hq_prospective_user')
    op.alter_column('hq_prospective_user', 'ignored',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text("'0'"),
               existing_nullable=True)
    op.drop_index(op.f('ix_hq_daily_deposit_log_dedup_key'), table_name='hq_daily_deposit_log')
    op.create_index('ix_hq_daily_deposit_log_dedup_key', 'hq_daily_deposit_log', ['dedup_key'], unique=False)
    op.create_index('dedup_key', 'hq_daily_deposit_log', ['dedup_key'], unique=True)
    op.alter_column('hq_daily_deposit_log', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('(now())'),
               existing_nullable=False)
    op.drop_constraint(None, 'external_ranking_reward_log', type_='foreignkey')
    op.create_foreign_key('external_ranking_reward_log_fk_v2_user', 'external_ranking_reward_log', 'v2_user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'external_ranking_data', type_='foreignkey')
    op.drop_constraint(None, 'external_ranking_daily_deposit_delta', type_='foreignkey')
    op.create_foreign_key('external_ranking_daily_deposit_delta_fk_v2_user', 'external_ranking_daily_deposit_delta', 'v2_user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'event_participation_log', type_='foreignkey')
    op.create_foreign_key('event_participation_log_fk_v2_user', 'event_participation_log', 'v2_user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'dice_log', type_='foreignkey')
    op.create_foreign_key('dice_log_fk_v2_user', 'dice_log', 'v2_user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'admin_message_inbox', type_='foreignkey')
    op.create_foreign_key('admin_message_inbox_fk_v2_user', 'admin_message_inbox', 'v2_user', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
