"""Add v2_server_config and v2_user_deposit_evidence

Revision ID: aad439cb38d2
Revises: 20260128_1800_add_v2_auth_tables
Create Date: 2026-01-29 14:19:52.479963+09:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'aad439cb38d2'
down_revision = '20260128_1800_add_v2_auth_tables'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('streak_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('day_number', sa.Integer(), nullable=False),
    sa.Column('reward_type', sa.String(length=50), nullable=False),
    sa.Column('reward_amount', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_streak_config_day_number'), 'streak_config', ['day_number'], unique=False)
    op.create_index(op.f('ix_streak_config_id'), 'streak_config', ['id'], unique=False)
    op.create_table('v2_server_config',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', mysql.JSON(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_index(op.f('ix_v2_server_config_key'), 'v2_server_config', ['key'], unique=False)
    op.create_table('user_streak',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('current_streak', sa.Integer(), nullable=False),
    sa.Column('last_hit_date', sa.DateTime(), nullable=True),
    sa.Column('total_hits', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_streak_id'), 'user_streak', ['id'], unique=False)
    op.create_index(op.f('ix_user_streak_user_id'), 'user_streak', ['user_id'], unique=False)
    op.create_table('v2_user_deposit_evidence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('tx_id', sa.String(length=200), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('claimed_amount', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROVISIONAL', 'VERIFIED', 'REJECTED', name='evidencestatus'), nullable=False),
    sa.Column('reward_json', sa.JSON(), nullable=True),
    sa.Column('matched_log_id', sa.Integer(), nullable=True),
    sa.Column('admin_memo', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['v2_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_v2_user_deposit_evidence_id'), 'v2_user_deposit_evidence', ['id'], unique=False)
    op.create_index(op.f('ix_v2_user_deposit_evidence_status'), 'v2_user_deposit_evidence', ['status'], unique=False)
    op.create_index('ix_v2_user_deposit_evidence_tx_id', 'v2_user_deposit_evidence', ['tx_id'], unique=True)
    op.create_index(op.f('ix_v2_user_deposit_evidence_user_id'), 'v2_user_deposit_evidence', ['user_id'], unique=False)
    op.alter_column('season_pass_config', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('season_pass_config', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('season_pass_level', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('season_pass_level', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('season_pass_progress', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('season_pass_progress', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('season_pass_reward_log', 'claimed_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('season_pass_reward_log', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('season_pass_stamp_log', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('trial_token_bucket', 'token_type',
               existing_type=mysql.ENUM('ROULETTE_TICKET', 'DICE_TICKET', 'LOTTERY_TICKET', 'ROULETTE_COIN', 'DICE_TOKEN', 'TRIAL_TICKET', 'TRIAL_TOKEN', 'GOLD_KEY_TICKET', 'DIAMOND_TICKET', 'GOLD_KEY', 'DIAMOND_KEY', 'GOLD_KEY_FRAGMENT', 'DIAMOND_FRAGMENT', 'DIAMOND_KEY_FRAGMENT', 'PUZZLE_C', 'PUZZLE_C1', 'PUZZLE_C2', 'PUZZLE_J', 'PUZZLE_M', 'DIAMOND', 'VAULT', collation='utf8mb4_unicode_ci'),
               type_=sa.Enum('ROULETTE_TICKET', 'DICE_TICKET', 'LOTTERY_TICKET', 'GOLD_KEY_TICKET', 'DIAMOND_TICKET', 'GOLD_KEY_FRAGMENT', 'DIAMOND_FRAGMENT', 'TRIAL_TICKET', 'DIAMOND', 'ROULETTE_COIN', 'DICE_TOKEN', 'GOLD_KEY', 'DIAMOND_KEY', 'DIAMOND_KEY_FRAGMENT', 'TRIAL_TOKEN', 'PUZZLE_C', 'PUZZLE_C1', 'PUZZLE_C2', 'PUZZLE_J', 'PUZZLE_M', 'VAULT', name='gametokentype'),
               existing_nullable=False)
    op.alter_column('user_game_wallet', 'token_type',
               existing_type=mysql.ENUM('ROULETTE_TICKET', 'DICE_TICKET', 'LOTTERY_TICKET', 'ROULETTE_COIN', 'DICE_TOKEN', 'TRIAL_TICKET', 'TRIAL_TOKEN', 'GOLD_KEY_TICKET', 'DIAMOND_TICKET', 'GOLD_KEY', 'DIAMOND_KEY', 'GOLD_KEY_FRAGMENT', 'DIAMOND_FRAGMENT', 'DIAMOND_KEY_FRAGMENT', 'PUZZLE_C', 'PUZZLE_C1', 'PUZZLE_C2', 'PUZZLE_J', 'PUZZLE_M', 'DIAMOND', 'VAULT', collation='utf8mb4_unicode_ci'),
               type_=sa.Enum('ROULETTE_TICKET', 'DICE_TICKET', 'LOTTERY_TICKET', 'GOLD_KEY_TICKET', 'DIAMOND_TICKET', 'GOLD_KEY_FRAGMENT', 'DIAMOND_FRAGMENT', 'TRIAL_TICKET', 'DIAMOND', 'ROULETTE_COIN', 'DICE_TOKEN', 'GOLD_KEY', 'DIAMOND_KEY', 'DIAMOND_KEY_FRAGMENT', 'TRIAL_TOKEN', 'PUZZLE_C', 'PUZZLE_C1', 'PUZZLE_C2', 'PUZZLE_J', 'PUZZLE_M', 'VAULT', name='gametokentype'),
               existing_nullable=False)
    op.alter_column('user_game_wallet_ledger', 'token_type',
               existing_type=mysql.ENUM('ROULETTE_TICKET', 'DICE_TICKET', 'LOTTERY_TICKET', 'ROULETTE_COIN', 'DICE_TOKEN', 'TRIAL_TICKET', 'TRIAL_TOKEN', 'GOLD_KEY_TICKET', 'DIAMOND_TICKET', 'GOLD_KEY', 'DIAMOND_KEY', 'GOLD_KEY_FRAGMENT', 'DIAMOND_FRAGMENT', 'DIAMOND_KEY_FRAGMENT', 'PUZZLE_C', 'PUZZLE_C1', 'PUZZLE_C2', 'PUZZLE_J', 'PUZZLE_M', 'DIAMOND', 'VAULT', collation='utf8mb4_unicode_ci'),
               type_=sa.Enum('ROULETTE_TICKET', 'DICE_TICKET', 'LOTTERY_TICKET', 'GOLD_KEY_TICKET', 'DIAMOND_TICKET', 'GOLD_KEY_FRAGMENT', 'DIAMOND_FRAGMENT', 'TRIAL_TICKET', 'DIAMOND', 'ROULETTE_COIN', 'DICE_TOKEN', 'GOLD_KEY', 'DIAMOND_KEY', 'DIAMOND_KEY_FRAGMENT', 'TRIAL_TOKEN', 'PUZZLE_C', 'PUZZLE_C1', 'PUZZLE_C2', 'PUZZLE_J', 'PUZZLE_M', 'VAULT', name='gametokentype'),
               existing_nullable=False)
    op.add_column('v2_golden_intervention_log', sa.Column('status', sa.String(length=20), nullable=False))
    op.alter_column('v2_golden_intervention_log', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=None,
               existing_nullable=False)
    op.create_index(op.f('ix_v2_golden_intervention_log_id'), 'v2_golden_intervention_log', ['id'], unique=False)
    op.create_index(op.f('ix_v2_golden_intervention_log_status'), 'v2_golden_intervention_log', ['status'], unique=False)
    op.alter_column('v2_user_auth_event', 'success',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=None,
               existing_comment='성공 여부',
               existing_nullable=False)
    op.alter_column('v2_user_auth_event', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=None,
               existing_comment='생성 시각',
               existing_nullable=False)
    op.drop_index('idx_v2_user_auth_event_created_at', table_name='v2_user_auth_event')
    op.drop_index('idx_v2_user_auth_event_user_id', table_name='v2_user_auth_event')
    op.create_index(op.f('ix_v2_user_auth_event_created_at'), 'v2_user_auth_event', ['created_at'], unique=False)
    op.create_index(op.f('ix_v2_user_auth_event_id'), 'v2_user_auth_event', ['id'], unique=False)
    op.create_index(op.f('ix_v2_user_auth_event_user_id'), 'v2_user_auth_event', ['user_id'], unique=False)
    op.alter_column('v2_user_refresh_token', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=None,
               existing_comment='생성 시각',
               existing_nullable=False)
    op.alter_column('v2_user_refresh_token', 'last_used_at',
               existing_type=mysql.DATETIME(),
               server_default=None,
               existing_comment='마지막 사용 시각',
               existing_nullable=False)
    op.drop_index('idx_v2_refresh_token_expires_at', table_name='v2_user_refresh_token')
    op.drop_index('idx_v2_refresh_token_jti', table_name='v2_user_refresh_token')
    op.drop_index('idx_v2_refresh_token_user_id', table_name='v2_user_refresh_token')
    op.drop_index('uq_v2_refresh_token_jti', table_name='v2_user_refresh_token')
    op.create_index(op.f('ix_v2_user_refresh_token_expires_at'), 'v2_user_refresh_token', ['expires_at'], unique=False)
    op.create_index(op.f('ix_v2_user_refresh_token_id'), 'v2_user_refresh_token', ['id'], unique=False)
    op.create_index(op.f('ix_v2_user_refresh_token_jti'), 'v2_user_refresh_token', ['jti'], unique=True)
    op.create_index(op.f('ix_v2_user_refresh_token_user_id'), 'v2_user_refresh_token', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_v2_user_refresh_token_user_id'), table_name='v2_user_refresh_token')
    op.drop_index(op.f('ix_v2_user_refresh_token_jti'), table_name='v2_user_refresh_token')
    op.drop_index(op.f('ix_v2_user_refresh_token_id'), table_name='v2_user_refresh_token')
    op.drop_index(op.f('ix_v2_user_refresh_token_expires_at'), table_name='v2_user_refresh_token')
    op.create_index('uq_v2_refresh_token_jti', 'v2_user_refresh_token', ['jti'], unique=True)
    op.create_index('idx_v2_refresh_token_user_id', 'v2_user_refresh_token', ['user_id'], unique=False)
    op.create_index('idx_v2_refresh_token_jti', 'v2_user_refresh_token', ['jti'], unique=False)
    op.create_index('idx_v2_refresh_token_expires_at', 'v2_user_refresh_token', ['expires_at'], unique=False)
    op.alter_column('v2_user_refresh_token', 'last_used_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('(now())'),
               existing_comment='마지막 사용 시각',
               existing_nullable=False)
    op.alter_column('v2_user_refresh_token', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('(now())'),
               existing_comment='생성 시각',
               existing_nullable=False)
    op.drop_index(op.f('ix_v2_user_auth_event_user_id'), table_name='v2_user_auth_event')
    op.drop_index(op.f('ix_v2_user_auth_event_id'), table_name='v2_user_auth_event')
    op.drop_index(op.f('ix_v2_user_auth_event_created_at'), table_name='v2_user_auth_event')
    op.create_index('idx_v2_user_auth_event_user_id', 'v2_user_auth_event', ['user_id'], unique=False)
    op.create_index('idx_v2_user_auth_event_created_at', 'v2_user_auth_event', ['created_at'], unique=False)
    op.alter_column('v2_user_auth_event', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('(now())'),
               existing_comment='생성 시각',
               existing_nullable=False)
    op.alter_column('v2_user_auth_event', 'success',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text("'1'"),
               existing_comment='성공 여부',
               existing_nullable=False)
    op.drop_index(op.f('ix_v2_golden_intervention_log_status'), table_name='v2_golden_intervention_log')
    op.drop_index(op.f('ix_v2_golden_intervention_log_id'), table_name='v2_golden_intervention_log')
    op.alter_column('v2_golden_intervention_log', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('(now())'),
               existing_nullable=False)
    op.drop_column('v2_golden_intervention_log', 'status')
    op.alter_column('user_game_wallet_ledger', 'token_type',
               existing_type=sa.Enum('ROULETTE_TICKET', 'DICE_TICKET', 'LOTTERY_TICKET', 'GOLD_KEY_TICKET', 'DIAMOND_TICKET', 'GOLD_KEY_FRAGMENT', 'DIAMOND_FRAGMENT', 'TRIAL_TICKET', 'DIAMOND', 'ROULETTE_COIN', 'DICE_TOKEN', 'GOLD_KEY', 'DIAMOND_KEY', 'DIAMOND_KEY_FRAGMENT', 'TRIAL_TOKEN', 'PUZZLE_C', 'PUZZLE_C1', 'PUZZLE_C2', 'PUZZLE_J', 'PUZZLE_M', 'VAULT', name='gametokentype'),
               type_=mysql.ENUM('ROULETTE_TICKET', 'DICE_TICKET', 'LOTTERY_TICKET', 'ROULETTE_COIN', 'DICE_TOKEN', 'TRIAL_TICKET', 'TRIAL_TOKEN', 'GOLD_KEY_TICKET', 'DIAMOND_TICKET', 'GOLD_KEY', 'DIAMOND_KEY', 'GOLD_KEY_FRAGMENT', 'DIAMOND_FRAGMENT', 'DIAMOND_KEY_FRAGMENT', 'PUZZLE_C', 'PUZZLE_C1', 'PUZZLE_C2', 'PUZZLE_J', 'PUZZLE_M', 'DIAMOND', 'VAULT', collation='utf8mb4_unicode_ci'),
               existing_nullable=False)
    op.alter_column('user_game_wallet', 'token_type',
               existing_type=sa.Enum('ROULETTE_TICKET', 'DICE_TICKET', 'LOTTERY_TICKET', 'GOLD_KEY_TICKET', 'DIAMOND_TICKET', 'GOLD_KEY_FRAGMENT', 'DIAMOND_FRAGMENT', 'TRIAL_TICKET', 'DIAMOND', 'ROULETTE_COIN', 'DICE_TOKEN', 'GOLD_KEY', 'DIAMOND_KEY', 'DIAMOND_KEY_FRAGMENT', 'TRIAL_TOKEN', 'PUZZLE_C', 'PUZZLE_C1', 'PUZZLE_C2', 'PUZZLE_J', 'PUZZLE_M', 'VAULT', name='gametokentype'),
               type_=mysql.ENUM('ROULETTE_TICKET', 'DICE_TICKET', 'LOTTERY_TICKET', 'ROULETTE_COIN', 'DICE_TOKEN', 'TRIAL_TICKET', 'TRIAL_TOKEN', 'GOLD_KEY_TICKET', 'DIAMOND_TICKET', 'GOLD_KEY', 'DIAMOND_KEY', 'GOLD_KEY_FRAGMENT', 'DIAMOND_FRAGMENT', 'DIAMOND_KEY_FRAGMENT', 'PUZZLE_C', 'PUZZLE_C1', 'PUZZLE_C2', 'PUZZLE_J', 'PUZZLE_M', 'DIAMOND', 'VAULT', collation='utf8mb4_unicode_ci'),
               existing_nullable=False)
    op.alter_column('trial_token_bucket', 'token_type',
               existing_type=sa.Enum('ROULETTE_TICKET', 'DICE_TICKET', 'LOTTERY_TICKET', 'GOLD_KEY_TICKET', 'DIAMOND_TICKET', 'GOLD_KEY_FRAGMENT', 'DIAMOND_FRAGMENT', 'TRIAL_TICKET', 'DIAMOND', 'ROULETTE_COIN', 'DICE_TOKEN', 'GOLD_KEY', 'DIAMOND_KEY', 'DIAMOND_KEY_FRAGMENT', 'TRIAL_TOKEN', 'PUZZLE_C', 'PUZZLE_C1', 'PUZZLE_C2', 'PUZZLE_J', 'PUZZLE_M', 'VAULT', name='gametokentype'),
               type_=mysql.ENUM('ROULETTE_TICKET', 'DICE_TICKET', 'LOTTERY_TICKET', 'ROULETTE_COIN', 'DICE_TOKEN', 'TRIAL_TICKET', 'TRIAL_TOKEN', 'GOLD_KEY_TICKET', 'DIAMOND_TICKET', 'GOLD_KEY', 'DIAMOND_KEY', 'GOLD_KEY_FRAGMENT', 'DIAMOND_FRAGMENT', 'DIAMOND_KEY_FRAGMENT', 'PUZZLE_C', 'PUZZLE_C1', 'PUZZLE_C2', 'PUZZLE_J', 'PUZZLE_M', 'DIAMOND', 'VAULT', collation='utf8mb4_unicode_ci'),
               existing_nullable=False)
    op.alter_column('season_pass_stamp_log', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.alter_column('season_pass_reward_log', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.alter_column('season_pass_reward_log', 'claimed_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.alter_column('season_pass_progress', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.alter_column('season_pass_progress', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.alter_column('season_pass_level', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.alter_column('season_pass_level', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.alter_column('season_pass_config', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.alter_column('season_pass_config', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.drop_index(op.f('ix_v2_user_deposit_evidence_user_id'), table_name='v2_user_deposit_evidence')
    op.drop_index('ix_v2_user_deposit_evidence_tx_id', table_name='v2_user_deposit_evidence')
    op.drop_index(op.f('ix_v2_user_deposit_evidence_status'), table_name='v2_user_deposit_evidence')
    op.drop_index(op.f('ix_v2_user_deposit_evidence_id'), table_name='v2_user_deposit_evidence')
    op.drop_table('v2_user_deposit_evidence')
    op.drop_index(op.f('ix_user_streak_user_id'), table_name='user_streak')
    op.drop_index(op.f('ix_user_streak_id'), table_name='user_streak')
    op.drop_table('user_streak')
    op.drop_index(op.f('ix_v2_server_config_key'), table_name='v2_server_config')
    op.drop_table('v2_server_config')
    op.drop_index(op.f('ix_streak_config_id'), table_name='streak_config')
    op.drop_index(op.f('ix_streak_config_day_number'), table_name='streak_config')
    op.drop_table('streak_config')
    # ### end Alembic commands ###
