"""add_roulette_grade_and_tokens

Revision ID: 23cb59c1173f
Revises: 20260116_0900_add_ops_eval_metrics
Create Date: 2026-01-16 12:36:52.443138+09:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '23cb59c1173f'
down_revision = '20260116_0900_add_ops_eval_metrics'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Focusing only on relevant changes (Roulette Config Grade)
    # Ignoring auto-generated noise for existing tables
    
    # op.alter_column('admin_message', ... ) 
    # ... (omitted noisy changes)
    
    op.add_column('roulette_config', sa.Column('grade', sa.String(length=20), server_default='COMMON', nullable=False))
    op.alter_column('season_pass_config', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('season_pass_config', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('season_pass_level', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('season_pass_level', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('season_pass_progress', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('season_pass_progress', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('season_pass_reward_log', 'claimed_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('season_pass_reward_log', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('season_pass_stamp_log', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.create_foreign_key(None, 'team_member', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index('idx_user_login_streak', table_name='user')
    op.drop_index('idx_user_streak', table_name='user')
    op.alter_column('user_idempotency_key', 'status',
               existing_type=mysql.VARCHAR(length=20),
               server_default=None,
               existing_nullable=False)
    op.alter_column('user_idempotency_key', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('user_idempotency_key', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=None,
               existing_nullable=False)
    op.drop_index('ix_user_idempotency_key_user_scope_created', table_name='user_idempotency_key')
    op.alter_column('user_identity_history', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('vault_ledger', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=None,
               existing_nullable=False)
    op.drop_constraint('vault_withdrawal_request_ibfk_1', 'vault_withdrawal_request', type_='foreignkey')
    op.create_foreign_key(None, 'vault_withdrawal_request', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vault_withdrawal_request', type_='foreignkey')
    op.create_foreign_key('vault_withdrawal_request_ibfk_1', 'vault_withdrawal_request', 'user', ['user_id'], ['id'])
    op.alter_column('vault_ledger', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('(now())'),
               existing_nullable=False)
    op.alter_column('user_identity_history', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.create_index('ix_user_idempotency_key_user_scope_created', 'user_idempotency_key', ['user_id', 'scope', 'created_at'], unique=False)
    op.alter_column('user_idempotency_key', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.alter_column('user_idempotency_key', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.alter_column('user_idempotency_key', 'status',
               existing_type=mysql.VARCHAR(length=20),
               server_default=sa.text("'IN_PROGRESS'"),
               existing_nullable=False)
    op.create_index('idx_user_streak', 'user', ['play_streak', 'last_play_date'], unique=False)
    op.create_index('idx_user_login_streak', 'user', ['login_streak'], unique=False)
    op.drop_constraint(None, 'team_member', type_='foreignkey')
    op.alter_column('season_pass_stamp_log', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.alter_column('season_pass_reward_log', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.alter_column('season_pass_reward_log', 'claimed_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.alter_column('season_pass_progress', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.alter_column('season_pass_progress', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.alter_column('season_pass_level', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.alter_column('season_pass_level', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.alter_column('season_pass_config', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.alter_column('season_pass_config', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.drop_column('roulette_config', 'grade')
    op.alter_column('ops_target_member', 'result_status',
               existing_type=mysql.VARCHAR(length=20),
               server_default=sa.text("'NONE'"),
               existing_nullable=False)
    op.alter_column('ops_target_member', 'status',
               existing_type=mysql.VARCHAR(length=20),
               server_default=sa.text("'PENDING'"),
               existing_nullable=False)
    op.alter_column('ops_target_list', 'is_processed',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text("'0'"),
               existing_nullable=False)
    op.alter_column('ops_target_list', 'count_snapshot',
               existing_type=mysql.INTEGER(),
               server_default=sa.text("'0'"),
               existing_nullable=False)
    op.alter_column('ops_plan_task', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.alter_column('ops_plan_task', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.alter_column('ops_plan_task', 'status',
               existing_type=mysql.VARCHAR(length=20),
               server_default=sa.text("'TODO'"),
               existing_nullable=False)
    op.alter_column('ops_plan_task', 'type',
               existing_type=mysql.VARCHAR(length=30),
               server_default=sa.text("'NOTE'"),
               existing_nullable=False)
    op.alter_column('ops_plan', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.alter_column('ops_plan', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.alter_column('ops_plan', 'status',
               existing_type=mysql.VARCHAR(length=20),
               server_default=sa.text("'DRAFT'"),
               existing_nullable=False)
    op.drop_index(op.f('ix_ops_log_entry_id'), table_name='ops_log_entry')
    op.alter_column('ops_log_entry', 'is_automated',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text("'0'"),
               existing_nullable=False)
    op.alter_column('ops_log_entry', 'target_model',
               existing_type=mysql.VARCHAR(length=50),
               server_default=sa.text("'NONE'"),
               existing_nullable=False)
    op.alter_column('ops_log_entry', 'timestamp',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.drop_index(op.f('ix_ops_eval_metrics_plan_id'), table_name='ops_eval_metrics')
    op.drop_index(op.f('ix_ops_eval_metrics_id'), table_name='ops_eval_metrics')
    op.alter_column('ops_daily_log', 'status',
               existing_type=mysql.VARCHAR(length=20),
               server_default=sa.text("'DRAFT'"),
               existing_nullable=False)
    op.alter_column('ops_campaign', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.alter_column('ops_campaign', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.alter_column('ops_campaign', 'status',
               existing_type=mysql.VARCHAR(length=20),
               server_default=sa.text("'DRAFT'"),
               existing_nullable=False)
    op.alter_column('mission', 'auto_claim',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text("'0'"),
               nullable=False)
    op.drop_constraint(None, 'external_ranking_reward_log', type_='foreignkey')
    op.drop_constraint(None, 'external_ranking_reward_log', type_='foreignkey')
    op.create_foreign_key('external_ranking_reward_log_ibfk_1', 'external_ranking_reward_log', 'external_ranking_data', ['data_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(None, 'external_ranking_data', type_='foreignkey')
    op.alter_column('external_ranking_daily_deposit_delta', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.alter_column('external_ranking_daily_deposit_delta', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.alter_column('external_ranking_daily_deposit_delta', 'deposit_delta',
               existing_type=mysql.INTEGER(),
               server_default=sa.text("'0'"),
               existing_nullable=False)
    op.drop_index(op.f('ix_event_participation_log_user_id'), table_name='event_participation_log')
    op.drop_index(op.f('ix_event_participation_log_participated_at'), table_name='event_participation_log')
    op.drop_index(op.f('ix_event_participation_log_id'), table_name='event_participation_log')
    op.drop_index(op.f('ix_event_participation_log_event_type'), table_name='event_participation_log')
    op.drop_index(op.f('ix_event_participation_log_event_id'), table_name='event_participation_log')
    op.create_index('ix_event_participation_user', 'event_participation_log', ['user_id'], unique=False)
    op.create_index('ix_event_participation_type', 'event_participation_log', ['event_type'], unique=False)
    op.create_index('ix_event_participation_time', 'event_participation_log', ['participated_at'], unique=False)
    op.create_index('ix_event_participation_event', 'event_participation_log', ['event_id'], unique=False)
    op.alter_column('event_participation_log', 'participated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.drop_index(op.f('ix_event_config_id'), table_name='event_config')
    op.drop_index(op.f('ix_event_config_event_type'), table_name='event_config')
    op.create_index('ix_event_config_type_active', 'event_config', ['event_type', 'is_active'], unique=False)
    op.alter_column('event_config', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.alter_column('event_config', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.alter_column('admin_message', 'is_deleted',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text("'0'"),
               existing_nullable=False)
    # ### end Alembic commands ###
