"""baseline_v2_snapshot

Revision ID: 3bc52f37e0c0
Revises: 
Create Date: 2026-01-19 09:04:43.302507+09:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3bc52f37e0c0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('target_type', sa.String(length=50), nullable=True),
    sa.Column('target_id', sa.String(length=100), nullable=True),
    sa.Column('before_json', sa.JSON().with_variant(mysql.JSON(), 'mysql'), nullable=True),
    sa.Column('after_json', sa.JSON().with_variant(mysql.JSON(), 'mysql'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_audit_log_admin_id'), 'admin_audit_log', ['admin_id'], unique=False)
    op.create_index(op.f('ix_admin_audit_log_id'), 'admin_audit_log', ['id'], unique=False)
    op.create_table('admin_message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sender_admin_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('target_type', sa.String(length=50), nullable=False),
    sa.Column('target_value', sa.String(length=255), nullable=True),
    sa.Column('channels', mysql.JSON(), nullable=True),
    sa.Column('recipient_count', sa.Integer(), nullable=True),
    sa.Column('read_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_message_id'), 'admin_message', ['id'], unique=False)
    op.create_table('app_ui_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key', name='uq_app_ui_config_key')
    )
    op.create_index(op.f('ix_app_ui_config_id'), 'app_ui_config', ['id'], unique=False)
    op.create_table('dice_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('max_daily_plays', sa.Integer(), nullable=False),
    sa.Column('win_reward_type', sa.String(length=50), nullable=False),
    sa.Column('win_reward_amount', sa.Integer(), nullable=False),
    sa.Column('draw_reward_type', sa.String(length=50), nullable=False),
    sa.Column('draw_reward_amount', sa.Integer(), nullable=False),
    sa.Column('lose_reward_type', sa.String(length=50), nullable=False),
    sa.Column('lose_reward_amount', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dice_config_id'), 'dice_config', ['id'], unique=False)
    op.create_table('event_config',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('multiplier', sa.Float(), nullable=True),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.Column('end_time', sa.Time(), nullable=True),
    sa.Column('target_segment', sa.String(length=50), nullable=True),
    sa.Column('config_json', sa.JSON().with_variant(mysql.JSON(), 'mysql'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_config_event_type'), 'event_config', ['event_type'], unique=False)
    op.create_index(op.f('ix_event_config_id'), 'event_config', ['id'], unique=False)
    op.create_index(op.f('ix_event_config_target_segment'), 'event_config', ['target_segment'], unique=False)
    op.create_table('feature_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('feature_type', sa.Enum('ROULETTE', 'DICE', 'LOTTERY', 'RANKING', 'SEASON_PASS', 'NONE', name='featuretype'), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('page_path', sa.String(length=100), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('config_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('feature_type', name='uq_feature_config_feature_type')
    )
    op.create_index(op.f('ix_feature_config_id'), 'feature_config', ['id'], unique=False)
    op.create_table('feature_schedule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('feature_type', sa.Enum('ROULETTE', 'DICE', 'LOTTERY', 'RANKING', 'SEASON_PASS', 'NONE', name='featuretype'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date', name='uq_feature_schedule_date')
    )
    op.create_index(op.f('ix_feature_schedule_id'), 'feature_schedule', ['id'], unique=False)
    op.create_table('lottery_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('max_daily_tickets', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lottery_config_id'), 'lottery_config', ['id'], unique=False)
    op.create_table('mission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.Enum('DAILY', 'WEEKLY', 'SPECIAL', 'NEW_USER', name='missioncategory'), nullable=False),
    sa.Column('logic_key', sa.String(length=100), nullable=False),
    sa.Column('action_type', sa.String(length=50), nullable=True),
    sa.Column('target_value', sa.Integer(), nullable=False),
    sa.Column('reward_type', sa.Enum('NONE', 'DIAMOND', 'GOLD_KEY', 'DIAMOND_KEY', 'CASH_UNLOCK', 'TICKET_BUNDLE', 'TICKET_ROULETTE', 'TICKET_LOTTERY', 'TICKET_DICE', 'POINT', name='missionrewardtype'), nullable=False),
    sa.Column('reward_amount', sa.Integer(), nullable=False),
    sa.Column('xp_reward', sa.Integer(), nullable=False),
    sa.Column('requires_approval', sa.Boolean(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.Column('end_time', sa.Time(), nullable=True),
    sa.Column('auto_claim', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mission_action_type'), 'mission', ['action_type'], unique=False)
    op.create_index(op.f('ix_mission_category'), 'mission', ['category'], unique=False)
    op.create_index(op.f('ix_mission_id'), 'mission', ['id'], unique=False)
    op.create_index(op.f('ix_mission_logic_key'), 'mission', ['logic_key'], unique=True)
    op.create_table('ops_campaign',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('owner_admin_id', sa.Integer(), nullable=True),
    sa.Column('goal_json', sa.JSON().with_variant(mysql.JSON(), 'mysql'), nullable=True),
    sa.Column('notes_md', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ops_campaign_id'), 'ops_campaign', ['id'], unique=False)
    op.create_table('ops_daily_log',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('theme_title', sa.String(length=200), nullable=True),
    sa.Column('manager_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('summary_md', sa.String(length=5000), nullable=True),
    sa.Column('kpi_snapshot', sa.JSON().with_variant(mysql.JSON(), 'mysql'), nullable=True),
    sa.PrimaryKeyConstraint('date')
    )
    op.create_index(op.f('ix_ops_daily_log_date'), 'ops_daily_log', ['date'], unique=False)
    op.create_table('roulette_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('ticket_type', sa.String(length=50), server_default='ROULETTE_COIN', nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('max_daily_spins', sa.Integer(), nullable=False),
    sa.Column('grade', sa.String(length=20), server_default='COMMON', nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roulette_config_id'), 'roulette_config', ['id'], unique=False)
    op.create_table('season_pass_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('season_name', sa.String(length=100), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('max_level', sa.Integer(), nullable=False),
    sa.Column('base_xp_per_stamp', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('start_date <= end_date', name='ck_season_dates_order'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('season_name', name='uq_season_name')
    )
    op.create_index(op.f('ix_season_pass_config_end_date'), 'season_pass_config', ['end_date'], unique=False)
    op.create_index(op.f('ix_season_pass_config_id'), 'season_pass_config', ['id'], unique=False)
    op.create_index(op.f('ix_season_pass_config_is_active'), 'season_pass_config', ['is_active'], unique=False)
    op.create_index(op.f('ix_season_pass_config_start_date'), 'season_pass_config', ['start_date'], unique=False)
    op.create_table('segment_rule',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('segment', sa.String(length=50), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('condition_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_segment_rule_name')
    )
    op.create_table('team',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('icon', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_team_name')
    )
    op.create_index(op.f('ix_team_id'), 'team', ['id'], unique=False)
    op.create_table('team_season',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('starts_at', sa.DateTime(), nullable=False),
    sa.Column('ends_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('rewards_schema', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_team_season_name')
    )
    op.create_index('idx_team_season_active', 'team_season', ['is_active'], unique=False)
    op.create_index('idx_team_season_time', 'team_season', ['starts_at', 'ends_at'], unique=False)
    op.create_index(op.f('ix_team_season_id'), 'team_season', ['id'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(length=100), nullable=False),
    sa.Column('nickname', sa.String(length=100), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('level', sa.Integer(), server_default='1', nullable=False),
    sa.Column('xp', sa.Integer(), server_default='0', nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('last_login_ip', sa.String(length=45), nullable=True),
    sa.Column('vault_balance', sa.Integer(), server_default='0', nullable=False),
    sa.Column('vault_locked_balance', sa.Integer(), server_default='0', nullable=False),
    sa.Column('vault_available_balance', sa.Integer(), server_default='0', nullable=False),
    sa.Column('vault_locked_expires_at', sa.DateTime(), nullable=True),
    sa.Column('cash_balance', sa.Integer(), server_default='0', nullable=False),
    sa.Column('vault_fill_used_at', sa.DateTime(), nullable=True),
    sa.Column('vault_spent_total', sa.Integer(), server_default='0', nullable=False),
    sa.Column('vault_spent_today', sa.Integer(), server_default='0', nullable=False),
    sa.Column('vault_spent_reset_date', sa.String(length=10), nullable=True),
    sa.Column('total_charge_amount', sa.Integer(), server_default='0', nullable=False),
    sa.Column('first_deposit_amount', sa.Integer(), server_default='0', nullable=False),
    sa.Column('first_deposit_at', sa.DateTime(), nullable=True),
    sa.Column('next_season_seed', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('diamond_key_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('last_free_ticket_claimed_at', sa.DateTime(), nullable=True),
    sa.Column('play_streak', sa.Integer(), server_default='0', nullable=False),
    sa.Column('last_play_date', sa.Date(), nullable=True),
    sa.Column('login_streak', sa.Integer(), server_default='0', nullable=False),
    sa.Column('last_streak_updated_at', sa.DateTime(), nullable=True),
    sa.Column('streak_vault_bonus_date', sa.Date(), nullable=True),
    sa.Column('streak_vault_bonus_started_at', sa.DateTime(), nullable=True),
    sa.Column('has_completed_onboarding', sa.Boolean(), nullable=True),
    sa.Column('telegram_id', sa.BigInteger(), nullable=True),
    sa.Column('telegram_username', sa.String(length=100), nullable=True),
    sa.Column('telegram_is_blocked', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('telegram_join_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('first_login_at', sa.DateTime(), nullable=True),
    sa.Column('telegram_link_nonce', sa.String(length=64), nullable=True),
    sa.Column('telegram_link_nonce_expires_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_id')
    )
    op.create_index(op.f('ix_user_created_at'), 'user', ['created_at'], unique=False)
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.create_index(op.f('ix_user_nickname'), 'user', ['nickname'], unique=False)
    op.create_index(op.f('ix_user_telegram_id'), 'user', ['telegram_id'], unique=True)
    op.create_table('vault_program',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('duration_hours', sa.Integer(), server_default='24', nullable=False),
    sa.Column('expire_policy', sa.String(length=30), server_default='FIXED_24H', nullable=False),
    sa.Column('unlock_rules_json', sa.JSON(), nullable=True),
    sa.Column('ui_copy_json', sa.JSON(), nullable=True),
    sa.Column('config_json', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_index(op.f('ix_vault_program_id'), 'vault_program', ['id'], unique=False)
    op.create_table('admin_message_inbox',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['admin_message.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_message_inbox_id'), 'admin_message_inbox', ['id'], unique=False)
    op.create_index(op.f('ix_admin_message_inbox_message_id'), 'admin_message_inbox', ['message_id'], unique=False)
    op.create_index(op.f('ix_admin_message_inbox_user_id'), 'admin_message_inbox', ['user_id'], unique=False)
    op.create_table('admin_user_profile',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(length=100), nullable=True),
    sa.Column('real_name', sa.String(length=100), nullable=True),
    sa.Column('phone_number', sa.String(length=50), nullable=True),
    sa.Column('telegram_id', sa.String(length=100), nullable=True),
    sa.Column('tags', mysql.JSON(), nullable=True),
    sa.Column('memo', sa.Text(), nullable=True),
    sa.Column('total_active_days', sa.Integer(), nullable=True),
    sa.Column('days_since_last_charge', sa.Integer(), nullable=True),
    sa.Column('last_active_date_str', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_admin_user_profile_external_id'), 'admin_user_profile', ['external_id'], unique=False)
    op.create_index(op.f('ix_admin_user_profile_telegram_id'), 'admin_user_profile', ['telegram_id'], unique=False)
    op.create_table('dice_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('config_id', sa.Integer(), nullable=False),
    sa.Column('user_dice_1', sa.Integer(), nullable=False),
    sa.Column('user_dice_2', sa.Integer(), nullable=False),
    sa.Column('user_sum', sa.Integer(), nullable=False),
    sa.Column('dealer_dice_1', sa.Integer(), nullable=False),
    sa.Column('dealer_dice_2', sa.Integer(), nullable=False),
    sa.Column('dealer_sum', sa.Integer(), nullable=False),
    sa.Column('result', sa.String(length=10), nullable=False),
    sa.Column('reward_type', sa.String(length=50), nullable=False),
    sa.Column('reward_amount', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['config_id'], ['dice_config.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dice_log_id'), 'dice_log', ['id'], unique=False)
    op.create_index('ix_dice_log_user_created_at', 'dice_log', ['user_id', 'created_at'], unique=False)
    op.create_table('event_participation_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.String(length=50), nullable=True),
    sa.Column('participated_at', sa.DateTime(), nullable=False),
    sa.Column('reward_type', sa.String(length=50), nullable=True),
    sa.Column('reward_amount', sa.Integer(), nullable=True),
    sa.Column('meta_json', sa.JSON().with_variant(mysql.JSON(), 'mysql'), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['event_config.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_participation_log_event_id'), 'event_participation_log', ['event_id'], unique=False)
    op.create_index(op.f('ix_event_participation_log_event_type'), 'event_participation_log', ['event_type'], unique=False)
    op.create_index(op.f('ix_event_participation_log_id'), 'event_participation_log', ['id'], unique=False)
    op.create_index(op.f('ix_event_participation_log_participated_at'), 'event_participation_log', ['participated_at'], unique=False)
    op.create_index(op.f('ix_event_participation_log_user_id'), 'event_participation_log', ['user_id'], unique=False)
    op.create_table('external_ranking_daily_deposit_delta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('kst_date', sa.Date(), nullable=False),
    sa.Column('deposit_delta', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'kst_date', name='uq_ext_rank_daily_deposit_user_date')
    )
    op.create_index(op.f('ix_external_ranking_daily_deposit_delta_id'), 'external_ranking_daily_deposit_delta', ['id'], unique=False)
    op.create_index(op.f('ix_external_ranking_daily_deposit_delta_kst_date'), 'external_ranking_daily_deposit_delta', ['kst_date'], unique=False)
    op.create_index(op.f('ix_external_ranking_daily_deposit_delta_user_id'), 'external_ranking_daily_deposit_delta', ['user_id'], unique=False)
    op.create_table('external_ranking_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('deposit_amount', sa.Integer(), nullable=False),
    sa.Column('play_count', sa.Integer(), nullable=False),
    sa.Column('deposit_remainder', sa.Integer(), nullable=False),
    sa.Column('daily_base_deposit', sa.Integer(), nullable=False),
    sa.Column('daily_base_play', sa.Integer(), nullable=False),
    sa.Column('last_daily_reset', sa.Date(), nullable=True),
    sa.Column('memo', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', name='uq_external_ranking_user')
    )
    op.create_index(op.f('ix_external_ranking_data_id'), 'external_ranking_data', ['id'], unique=False)
    op.create_index(op.f('ix_external_ranking_data_user_id'), 'external_ranking_data', ['user_id'], unique=False)
    op.create_table('lottery_prize',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('config_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('reward_type', sa.String(length=50), nullable=False),
    sa.Column('reward_amount', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Integer(), nullable=False),
    sa.Column('stock', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('stock IS NULL OR stock >= 0', name='ck_lottery_prize_stock_non_negative'),
    sa.CheckConstraint('weight >= 0', name='ck_lottery_prize_weight_non_negative'),
    sa.ForeignKeyConstraint(['config_id'], ['lottery_config.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('config_id', 'label', name='uq_lottery_prize_label')
    )
    op.create_index(op.f('ix_lottery_prize_id'), 'lottery_prize', ['id'], unique=False)
    op.create_table('ops_log_entry',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('daily_log_date', sa.Date(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('action_code', sa.String(length=100), nullable=False),
    sa.Column('target_model', sa.String(length=50), nullable=False),
    sa.Column('target_id', sa.String(length=100), nullable=True),
    sa.Column('meta_data', sa.JSON().with_variant(mysql.JSON(), 'mysql'), nullable=False),
    sa.Column('is_automated', sa.Boolean(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=False),
    sa.Column('ref_id', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['daily_log_date'], ['ops_daily_log.date'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ref_id')
    )
    op.create_index('ix_ops_log_entry_daily_log_date', 'ops_log_entry', ['daily_log_date'], unique=False)
    op.create_index(op.f('ix_ops_log_entry_id'), 'ops_log_entry', ['id'], unique=False)
    op.create_index('ix_ops_log_entry_ref_id_unique', 'ops_log_entry', ['ref_id'], unique=True)
    op.create_index(op.f('ix_ops_log_entry_target_id'), 'ops_log_entry', ['target_id'], unique=False)
    op.create_index(op.f('ix_ops_log_entry_timestamp'), 'ops_log_entry', ['timestamp'], unique=False)
    op.create_table('ops_plan',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('plan_date', sa.Date(), nullable=False),
    sa.Column('theme_title', sa.String(length=200), nullable=True),
    sa.Column('key_message', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('closing_summary_md', sa.Text(), nullable=True),
    sa.Column('kpi_snapshot_json', sa.JSON().with_variant(mysql.JSON(), 'mysql'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['ops_campaign.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('campaign_id', 'plan_date', name='uq_ops_plan_campaign_date')
    )
    op.create_index(op.f('ix_ops_plan_campaign_id'), 'ops_plan', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_ops_plan_id'), 'ops_plan', ['id'], unique=False)
    op.create_index(op.f('ix_ops_plan_plan_date'), 'ops_plan', ['plan_date'], unique=False)
    op.create_table('ranking_daily',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('display_name', sa.String(length=50), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date', 'rank', name='uq_ranking_daily_date_rank')
    )
    op.create_index(op.f('ix_ranking_daily_id'), 'ranking_daily', ['id'], unique=False)
    op.create_table('retention_roi_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('predicted_ltv', sa.Float(), nullable=False),
    sa.Column('marketing_cost', sa.Float(), nullable=False),
    sa.Column('roi_percent', sa.Float(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=True),
    sa.Column('reward_type', sa.String(length=50), nullable=True),
    sa.Column('reward_amount', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_retention_roi_log_created_at'), 'retention_roi_log', ['created_at'], unique=False)
    op.create_index(op.f('ix_retention_roi_log_id'), 'retention_roi_log', ['id'], unique=False)
    op.create_index(op.f('ix_retention_roi_log_user_id'), 'retention_roi_log', ['user_id'], unique=False)
    op.create_table('roulette_segment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('config_id', sa.Integer(), nullable=False),
    sa.Column('slot_index', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=50), nullable=False),
    sa.Column('reward_type', sa.String(length=50), nullable=False),
    sa.Column('reward_amount', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Integer(), nullable=False),
    sa.Column('is_jackpot', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('slot_index >= 0 AND slot_index <= 5', name='ck_roulette_segment_slot_range'),
    sa.CheckConstraint('weight >= 0', name='ck_roulette_segment_weight_non_negative'),
    sa.ForeignKeyConstraint(['config_id'], ['roulette_config.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('config_id', 'slot_index', name='uq_roulette_segment_slot')
    )
    op.create_index(op.f('ix_roulette_segment_id'), 'roulette_segment', ['id'], unique=False)
    op.create_table('season_pass_level',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('required_xp', sa.Integer(), nullable=False),
    sa.Column('reward_type', sa.String(length=50), nullable=False),
    sa.Column('reward_amount', sa.Integer(), nullable=False),
    sa.Column('auto_claim', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['season_id'], ['season_pass_config.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('season_id', 'level', name='uq_season_level')
    )
    op.create_index(op.f('ix_season_pass_level_id'), 'season_pass_level', ['id'], unique=False)
    op.create_table('season_pass_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('current_level', sa.Integer(), nullable=False),
    sa.Column('current_xp', sa.Integer(), nullable=False),
    sa.Column('total_stamps', sa.Integer(), nullable=False),
    sa.Column('last_stamp_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['season_id'], ['season_pass_config.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'season_id', name='uq_user_season_progress')
    )
    op.create_index(op.f('ix_season_pass_progress_id'), 'season_pass_progress', ['id'], unique=False)
    op.create_table('survey',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'PAUSED', 'ARCHIVED', name='surveystatus'), nullable=False),
    sa.Column('channel', sa.Enum('GLOBAL', 'SEASON_PASS', 'ROULETTE', 'DICE', 'LOTTERY', 'TEAM_BATTLE', name='surveychannel'), nullable=False),
    sa.Column('target_segment_json', sa.JSON(), nullable=True),
    sa.Column('reward_json', sa.JSON(), nullable=True),
    sa.Column('auto_launch', sa.Boolean(), nullable=False),
    sa.Column('start_at', sa.DateTime(), nullable=True),
    sa.Column('end_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('team_event_log',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('delta', sa.Integer(), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['season_id'], ['team_season.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_tel_season_team', 'team_event_log', ['season_id', 'team_id', 'created_at'], unique=False)
    op.create_index('idx_tel_user', 'team_event_log', ['user_id'], unique=False)
    op.create_table('team_member',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=10), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index('idx_team_member_team', 'team_member', ['team_id'], unique=False)
    op.create_table('team_score',
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('points', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['season_id'], ['team_season.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('team_id', 'season_id'),
    sa.UniqueConstraint('team_id', 'season_id', name='uq_team_score')
    )
    op.create_index('idx_team_score_points', 'team_score', ['season_id', 'points'], unique=False)
    op.create_table('telegram_link_code',
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('client_ip', sa.String(length=50), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_index(op.f('ix_telegram_link_code_code'), 'telegram_link_code', ['code'], unique=False)
    op.create_index(op.f('ix_telegram_link_code_user_id'), 'telegram_link_code', ['user_id'], unique=False)
    op.create_table('trial_token_bucket',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_type', sa.Enum('ROULETTE_COIN', 'DICE_TOKEN', 'TRIAL_TOKEN', 'LOTTERY_TICKET', 'GOLD_KEY', 'DIAMOND_KEY', 'GOLD_KEY_FRAGMENT', 'DIAMOND_KEY_FRAGMENT', 'PUZZLE_C', 'PUZZLE_C1', 'PUZZLE_C2', 'PUZZLE_J', 'PUZZLE_M', 'DIAMOND', 'VAULT', name='gametokentype'), nullable=False),
    sa.Column('balance', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'token_type', name='uq_trial_token_bucket_user_token')
    )
    op.create_index(op.f('ix_trial_token_bucket_id'), 'trial_token_bucket', ['id'], unique=False)
    op.create_index(op.f('ix_trial_token_bucket_user_id'), 'trial_token_bucket', ['user_id'], unique=False)
    op.create_table('user_activity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('last_charge_at', sa.DateTime(), nullable=True),
    sa.Column('last_play_at', sa.DateTime(), nullable=True),
    sa.Column('roulette_plays', sa.Integer(), server_default='0', nullable=False),
    sa.Column('dice_plays', sa.Integer(), server_default='0', nullable=False),
    sa.Column('lottery_plays', sa.Integer(), server_default='0', nullable=False),
    sa.Column('total_play_duration', sa.Integer(), server_default='0', nullable=False),
    sa.Column('last_bonus_used_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', name='uq_user_activity_user')
    )
    op.create_index(op.f('ix_user_activity_id'), 'user_activity', ['id'], unique=False)
    op.create_index(op.f('ix_user_activity_user_id'), 'user_activity', ['user_id'], unique=False)
    op.create_index('ix_user_activity_user_updated_at', 'user_activity', ['user_id', 'updated_at'], unique=False)
    op.create_table('user_activity_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.String(length=36), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', name='uq_user_activity_event_event_id')
    )
    op.create_index(op.f('ix_user_activity_event_id'), 'user_activity_event', ['id'], unique=False)
    op.create_index('ix_user_activity_event_user_created', 'user_activity_event', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_user_activity_event_user_id'), 'user_activity_event', ['user_id'], unique=False)
    op.create_table('user_cash_ledger',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('delta', sa.Integer(), nullable=False),
    sa.Column('balance_after', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=100), nullable=True),
    sa.Column('label', sa.String(length=255), nullable=True),
    sa.Column('meta_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_cash_ledger_id'), 'user_cash_ledger', ['id'], unique=False)
    op.create_index(op.f('ix_user_cash_ledger_user_id'), 'user_cash_ledger', ['user_id'], unique=False)
    op.create_table('user_event_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('feature_type', sa.String(length=30), nullable=False),
    sa.Column('event_name', sa.String(length=50), nullable=False),
    sa.Column('meta_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_user_event_log_event_name', 'user_event_log', ['event_name'], unique=False)
    op.create_index(op.f('ix_user_event_log_id'), 'user_event_log', ['id'], unique=False)
    op.create_index('ix_user_event_log_user_created_at', 'user_event_log', ['user_id', 'created_at'], unique=False)
    op.create_table('user_game_wallet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_type', sa.Enum('ROULETTE_COIN', 'DICE_TOKEN', 'TRIAL_TOKEN', 'LOTTERY_TICKET', 'GOLD_KEY', 'DIAMOND_KEY', 'GOLD_KEY_FRAGMENT', 'DIAMOND_KEY_FRAGMENT', 'PUZZLE_C', 'PUZZLE_C1', 'PUZZLE_C2', 'PUZZLE_J', 'PUZZLE_M', 'DIAMOND', 'VAULT', name='gametokentype'), nullable=False),
    sa.Column('balance', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'token_type', name='uq_user_token_type')
    )
    op.create_index(op.f('ix_user_game_wallet_id'), 'user_game_wallet', ['id'], unique=False)
    op.create_index(op.f('ix_user_game_wallet_token_type'), 'user_game_wallet', ['token_type'], unique=False)
    op.create_index(op.f('ix_user_game_wallet_user_id'), 'user_game_wallet', ['user_id'], unique=False)
    op.create_table('user_game_wallet_ledger',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_type', sa.Enum('ROULETTE_COIN', 'DICE_TOKEN', 'TRIAL_TOKEN', 'LOTTERY_TICKET', 'GOLD_KEY', 'DIAMOND_KEY', 'GOLD_KEY_FRAGMENT', 'DIAMOND_KEY_FRAGMENT', 'PUZZLE_C', 'PUZZLE_C1', 'PUZZLE_C2', 'PUZZLE_J', 'PUZZLE_M', 'DIAMOND', 'VAULT', name='gametokentype'), nullable=False),
    sa.Column('delta', sa.Integer(), nullable=False),
    sa.Column('balance_after', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=100), nullable=True),
    sa.Column('label', sa.String(length=255), nullable=True),
    sa.Column('meta_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_game_wallet_ledger_created_at'), 'user_game_wallet_ledger', ['created_at'], unique=False)
    op.create_index(op.f('ix_user_game_wallet_ledger_id'), 'user_game_wallet_ledger', ['id'], unique=False)
    op.create_index(op.f('ix_user_game_wallet_ledger_token_type'), 'user_game_wallet_ledger', ['token_type'], unique=False)
    op.create_index(op.f('ix_user_game_wallet_ledger_user_id'), 'user_game_wallet_ledger', ['user_id'], unique=False)
    op.create_table('user_idempotency_key',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('scope', sa.String(length=50), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('request_hash', sa.String(length=64), nullable=False),
    sa.Column('request_json', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('response_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'scope', 'idempotency_key', name='uq_user_idempotency_key_user_scope_key')
    )
    op.create_index(op.f('ix_user_idempotency_key_id'), 'user_idempotency_key', ['id'], unique=False)
    op.create_index(op.f('ix_user_idempotency_key_scope'), 'user_idempotency_key', ['scope'], unique=False)
    op.create_index(op.f('ix_user_idempotency_key_status'), 'user_idempotency_key', ['status'], unique=False)
    op.create_index(op.f('ix_user_idempotency_key_user_id'), 'user_idempotency_key', ['user_id'], unique=False)
    op.create_table('user_identity_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('field_name', sa.String(length=50), nullable=False),
    sa.Column('old_value', sa.String(length=255), nullable=True),
    sa.Column('new_value', sa.String(length=255), nullable=True),
    sa.Column('changed_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_identity_history_user_id'), 'user_identity_history', ['user_id'], unique=False)
    op.create_table('user_inventory_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('item_type', sa.String(length=50), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'item_type', name='uq_user_inventory_item_user_item')
    )
    op.create_index(op.f('ix_user_inventory_item_id'), 'user_inventory_item', ['id'], unique=False)
    op.create_index(op.f('ix_user_inventory_item_item_type'), 'user_inventory_item', ['item_type'], unique=False)
    op.create_index(op.f('ix_user_inventory_item_user_id'), 'user_inventory_item', ['user_id'], unique=False)
    op.create_table('user_inventory_ledger',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('item_type', sa.String(length=50), nullable=False),
    sa.Column('change_amount', sa.Integer(), nullable=False),
    sa.Column('balance_after', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=100), nullable=False),
    sa.Column('related_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_inventory_ledger_id'), 'user_inventory_ledger', ['id'], unique=False)
    op.create_index(op.f('ix_user_inventory_ledger_item_type'), 'user_inventory_ledger', ['item_type'], unique=False)
    op.create_index(op.f('ix_user_inventory_ledger_user_id'), 'user_inventory_ledger', ['user_id'], unique=False)
    op.create_table('user_level_progress',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('xp', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('user_level_reward_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('reward_type', sa.String(length=50), nullable=False),
    sa.Column('reward_payload', sa.JSON(), nullable=True),
    sa.Column('auto_granted', sa.Boolean(), nullable=False),
    sa.Column('granted_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'level', name='uq_user_level_reward')
    )
    op.create_index(op.f('ix_user_level_reward_log_id'), 'user_level_reward_log', ['id'], unique=False)
    op.create_table('user_mission_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('mission_id', sa.Integer(), nullable=False),
    sa.Column('current_value', sa.Integer(), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=True),
    sa.Column('is_claimed', sa.Boolean(), nullable=True),
    sa.Column('approval_status', sa.Enum('NONE', 'PENDING', 'APPROVED', 'REJECTED', name='approvalstatus'), server_default='NONE', nullable=False),
    sa.Column('reset_date', sa.String(length=50), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['mission_id'], ['mission.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'mission_id', 'reset_date', name='uq_user_mission_reset')
    )
    op.create_index(op.f('ix_user_mission_progress_id'), 'user_mission_progress', ['id'], unique=False)
    op.create_index(op.f('ix_user_mission_progress_mission_id'), 'user_mission_progress', ['mission_id'], unique=False)
    op.create_index(op.f('ix_user_mission_progress_reset_date'), 'user_mission_progress', ['reset_date'], unique=False)
    op.create_index(op.f('ix_user_mission_progress_user_id'), 'user_mission_progress', ['user_id'], unique=False)
    op.create_table('user_retention_state',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('churn_probability_score', sa.Float(), nullable=False),
    sa.Column('predicted_ltv', sa.Float(), nullable=False),
    sa.Column('current_win_loss_streak', sa.Integer(), nullable=False),
    sa.Column('session_balance_delta', sa.Float(), nullable=False),
    sa.Column('bet_size_variation_score', sa.Float(), nullable=False),
    sa.Column('loyalty_frequency_score', sa.Integer(), nullable=False),
    sa.Column('psychological_state', sa.Enum('IN_FLOW', 'BORED', 'FRUSTRATED', 'TILTED', name='retention_psych_state'), nullable=False),
    sa.Column('user_segment_tag', sa.Enum('HIGH_ROLLER', 'CASUAL_LOYAL', 'NEW_USER', 'CHURN_RISK', name='retention_segment_tag'), nullable=False),
    sa.Column('last_intervention_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('user_segment',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('segment', sa.String(length=50), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('user_xp_event_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('delta', sa.Integer(), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_user_xp_event_log_id'), 'user_xp_event_log', ['id'], unique=False)
    op.create_table('vault_earn_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('earn_event_id', sa.String(length=128), nullable=False),
    sa.Column('earn_type', sa.String(length=50), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('reward_kind', sa.String(length=50), nullable=True),
    sa.Column('game_type', sa.String(length=50), nullable=True),
    sa.Column('token_type', sa.String(length=50), nullable=True),
    sa.Column('payout_raw_json', sa.JSON().with_variant(mysql.JSON(), 'mysql'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vault_earn_event_id'), 'vault_earn_event', ['id'], unique=False)
    op.create_index('ix_vault_earn_event_user_created_at', 'vault_earn_event', ['user_id', 'created_at'], unique=False)
    op.create_index('uq_vault_earn_event_earn_event_id', 'vault_earn_event', ['earn_event_id'], unique=True)
    op.create_table('vault_ledger',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('balance_after', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('ref_type', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vault_ledger_id'), 'vault_ledger', ['id'], unique=False)
    op.create_index(op.f('ix_vault_ledger_user_id'), 'vault_ledger', ['user_id'], unique=False)
    op.create_table('vault_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('program_id', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(length=20), server_default='LOCKED', nullable=False),
    sa.Column('locked_amount', sa.Integer(), server_default='0', nullable=False),
    sa.Column('available_amount', sa.Integer(), server_default='0', nullable=False),
    sa.Column('progress_json', sa.JSON(), nullable=True),
    sa.Column('locked_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['program_id'], ['vault_program.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vault_status_id'), 'vault_status', ['id'], unique=False)
    op.create_index(op.f('ix_vault_status_program_id'), 'vault_status', ['program_id'], unique=False)
    op.create_index(op.f('ix_vault_status_user_id'), 'vault_status', ['user_id'], unique=False)
    op.create_table('vault_withdrawal_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('admin_memo', sa.String(length=255), nullable=True),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('processed_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vault_withdrawal_request_id'), 'vault_withdrawal_request', ['id'], unique=False)
    op.create_index(op.f('ix_vault_withdrawal_request_user_id'), 'vault_withdrawal_request', ['user_id'], unique=False)
    op.create_table('external_ranking_reward_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('reward_type', sa.String(length=50), nullable=False),
    sa.Column('reward_amount', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=100), nullable=False),
    sa.Column('season_name', sa.String(length=50), nullable=False),
    sa.Column('data_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['data_id'], ['external_ranking_data.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_external_ranking_reward_log_id'), 'external_ranking_reward_log', ['id'], unique=False)
    op.create_index(op.f('ix_external_ranking_reward_log_user_id'), 'external_ranking_reward_log', ['user_id'], unique=False)
    op.create_table('lottery_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('config_id', sa.Integer(), nullable=False),
    sa.Column('prize_id', sa.Integer(), nullable=False),
    sa.Column('reward_type', sa.String(length=50), nullable=False),
    sa.Column('reward_amount', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['config_id'], ['lottery_config.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['prize_id'], ['lottery_prize.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lottery_log_id'), 'lottery_log', ['id'], unique=False)
    op.create_index('ix_lottery_log_user_created_at', 'lottery_log', ['user_id', 'created_at'], unique=False)
    op.create_table('ops_eval_metrics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('eval_type', sa.String(length=10), nullable=False),
    sa.Column('metrics_json', sa.JSON().with_variant(mysql.JSON(), 'mysql'), nullable=False),
    sa.Column('grade', sa.String(length=5), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['ops_plan.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ops_eval_metrics_created_at', 'ops_eval_metrics', ['created_at'], unique=False)
    op.create_index(op.f('ix_ops_eval_metrics_id'), 'ops_eval_metrics', ['id'], unique=False)
    op.create_index('ix_ops_eval_metrics_plan_eval_type', 'ops_eval_metrics', ['plan_id', 'eval_type'], unique=False)
    op.create_index(op.f('ix_ops_eval_metrics_plan_id'), 'ops_eval_metrics', ['plan_id'], unique=False)
    op.create_table('ops_plan_task',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('slot_time', sa.String(length=10), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('memo', sa.Text(), nullable=True),
    sa.Column('payload_json', sa.JSON().with_variant(mysql.JSON(), 'mysql'), nullable=True),
    sa.Column('executed_at', sa.DateTime(), nullable=True),
    sa.Column('actor_admin_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['ops_plan.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ops_plan_task_id'), 'ops_plan_task', ['id'], unique=False)
    op.create_index(op.f('ix_ops_plan_task_plan_id'), 'ops_plan_task', ['plan_id'], unique=False)
    op.create_index('ix_ops_plan_task_plan_id_status', 'ops_plan_task', ['plan_id', 'status'], unique=False)
    op.create_table('ops_target_list',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('source_params', sa.JSON().with_variant(mysql.JSON(), 'mysql'), nullable=True),
    sa.Column('count_snapshot', sa.Integer(), nullable=False),
    sa.Column('is_processed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['ops_plan.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ops_target_list_id'), 'ops_target_list', ['id'], unique=False)
    op.create_index(op.f('ix_ops_target_list_plan_id'), 'ops_target_list', ['plan_id'], unique=False)
    op.create_table('roulette_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('config_id', sa.Integer(), nullable=False),
    sa.Column('segment_id', sa.Integer(), nullable=False),
    sa.Column('reward_type', sa.String(length=50), nullable=False),
    sa.Column('reward_amount', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['config_id'], ['roulette_config.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['segment_id'], ['roulette_segment.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roulette_log_id'), 'roulette_log', ['id'], unique=False)
    op.create_index('ix_roulette_log_user_created_at', 'roulette_log', ['user_id', 'created_at'], unique=False)
    op.create_table('season_pass_reward_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('progress_id', sa.Integer(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('reward_type', sa.String(length=50), nullable=False),
    sa.Column('reward_amount', sa.Integer(), nullable=False),
    sa.Column('claimed_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['progress_id'], ['season_pass_progress.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['season_id'], ['season_pass_config.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'season_id', 'level', name='uq_reward_user_season_level')
    )
    op.create_index(op.f('ix_season_pass_reward_log_id'), 'season_pass_reward_log', ['id'], unique=False)
    op.create_table('season_pass_stamp_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('progress_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('period_key', sa.String(length=32), nullable=False),
    sa.Column('stamp_count', sa.Integer(), nullable=False),
    sa.Column('source_feature_type', sa.String(length=30), nullable=False),
    sa.Column('xp_earned', sa.Integer(), nullable=False),
    sa.Column('reward_type', sa.String(length=50), nullable=False),
    sa.Column('reward_amount', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['progress_id'], ['season_pass_progress.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['season_id'], ['season_pass_config.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'season_id', 'source_feature_type', 'period_key', name='uq_stamp_user_season_period')
    )
    op.create_index(op.f('ix_season_pass_stamp_log_id'), 'season_pass_stamp_log', ['id'], unique=False)
    op.create_table('survey_question',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('survey_id', sa.Integer(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('randomize_group', sa.String(length=50), nullable=True),
    sa.Column('question_type', sa.Enum('SINGLE_CHOICE', 'MULTI_CHOICE', 'LIKERT', 'TEXT', 'NUMBER', name='surveyquestiontype'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('helper_text', sa.String(length=255), nullable=True),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('config_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['survey_id'], ['survey.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('survey_id', 'order_index', name='uq_survey_question_order')
    )
    op.create_table('survey_trigger_rule',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('survey_id', sa.Integer(), nullable=False),
    sa.Column('trigger_type', sa.Enum('LEVEL_UP', 'INACTIVE_DAYS', 'GAME_RESULT', 'MANUAL_PUSH', name='surveytriggertype'), nullable=False),
    sa.Column('trigger_config_json', sa.JSON(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('cooldown_hours', sa.Integer(), nullable=False),
    sa.Column('max_per_user', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['survey_id'], ['survey.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ops_target_member',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('target_list_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('data', sa.JSON().with_variant(mysql.JSON(), 'mysql'), nullable=True),
    sa.Column('result_status', sa.String(length=20), nullable=False),
    sa.Column('converted_at', sa.DateTime(), nullable=True),
    sa.Column('conversion_value', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['target_list_id'], ['ops_target_list.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('target_list_id', 'user_id', name='uq_target_member_list_user')
    )
    op.create_index(op.f('ix_ops_target_member_id'), 'ops_target_member', ['id'], unique=False)
    op.create_index(op.f('ix_ops_target_member_target_list_id'), 'ops_target_member', ['target_list_id'], unique=False)
    op.create_index(op.f('ix_ops_target_member_user_id'), 'ops_target_member', ['user_id'], unique=False)
    op.create_table('survey_option',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(length=100), nullable=False),
    sa.Column('label', sa.String(length=150), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['survey_question.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('survey_response',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('survey_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('trigger_rule_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', 'DROPPED', 'EXPIRED', name='surveyresponsestatus'), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('dropped_at', sa.DateTime(), nullable=True),
    sa.Column('reward_status', sa.Enum('NONE', 'SCHEDULED', 'GRANTED', 'FAILED', name='surveyrewardstatus'), nullable=False),
    sa.Column('reward_payload', sa.JSON(), nullable=True),
    sa.Column('last_question_id', sa.Integer(), nullable=True),
    sa.Column('last_activity_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("reward_status IN ('NONE','SCHEDULED','GRANTED','FAILED')", name='ck_survey_reward_status'),
    sa.ForeignKeyConstraint(['last_question_id'], ['survey_question.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['survey_id'], ['survey.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trigger_rule_id'], ['survey_trigger_rule.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('survey_response_answer',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('response_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('option_id', sa.Integer(), nullable=True),
    sa.Column('answer_text', sa.Text(), nullable=True),
    sa.Column('answer_number', sa.Integer(), nullable=True),
    sa.Column('meta_json', sa.JSON(), nullable=True),
    sa.Column('answered_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['option_id'], ['survey_option.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['question_id'], ['survey_question.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['response_id'], ['survey_response.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('response_id', 'question_id', name='uq_response_question')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('survey_response_answer')
    op.drop_table('survey_response')
    op.drop_table('survey_option')
    op.drop_index(op.f('ix_ops_target_member_user_id'), table_name='ops_target_member')
    op.drop_index(op.f('ix_ops_target_member_target_list_id'), table_name='ops_target_member')
    op.drop_index(op.f('ix_ops_target_member_id'), table_name='ops_target_member')
    op.drop_table('ops_target_member')
    op.drop_table('survey_trigger_rule')
    op.drop_table('survey_question')
    op.drop_index(op.f('ix_season_pass_stamp_log_id'), table_name='season_pass_stamp_log')
    op.drop_table('season_pass_stamp_log')
    op.drop_index(op.f('ix_season_pass_reward_log_id'), table_name='season_pass_reward_log')
    op.drop_table('season_pass_reward_log')
    op.drop_index('ix_roulette_log_user_created_at', table_name='roulette_log')
    op.drop_index(op.f('ix_roulette_log_id'), table_name='roulette_log')
    op.drop_table('roulette_log')
    op.drop_index(op.f('ix_ops_target_list_plan_id'), table_name='ops_target_list')
    op.drop_index(op.f('ix_ops_target_list_id'), table_name='ops_target_list')
    op.drop_table('ops_target_list')
    op.drop_index('ix_ops_plan_task_plan_id_status', table_name='ops_plan_task')
    op.drop_index(op.f('ix_ops_plan_task_plan_id'), table_name='ops_plan_task')
    op.drop_index(op.f('ix_ops_plan_task_id'), table_name='ops_plan_task')
    op.drop_table('ops_plan_task')
    op.drop_index(op.f('ix_ops_eval_metrics_plan_id'), table_name='ops_eval_metrics')
    op.drop_index('ix_ops_eval_metrics_plan_eval_type', table_name='ops_eval_metrics')
    op.drop_index(op.f('ix_ops_eval_metrics_id'), table_name='ops_eval_metrics')
    op.drop_index('ix_ops_eval_metrics_created_at', table_name='ops_eval_metrics')
    op.drop_table('ops_eval_metrics')
    op.drop_index('ix_lottery_log_user_created_at', table_name='lottery_log')
    op.drop_index(op.f('ix_lottery_log_id'), table_name='lottery_log')
    op.drop_table('lottery_log')
    op.drop_index(op.f('ix_external_ranking_reward_log_user_id'), table_name='external_ranking_reward_log')
    op.drop_index(op.f('ix_external_ranking_reward_log_id'), table_name='external_ranking_reward_log')
    op.drop_table('external_ranking_reward_log')
    op.drop_index(op.f('ix_vault_withdrawal_request_user_id'), table_name='vault_withdrawal_request')
    op.drop_index(op.f('ix_vault_withdrawal_request_id'), table_name='vault_withdrawal_request')
    op.drop_table('vault_withdrawal_request')
    op.drop_index(op.f('ix_vault_status_user_id'), table_name='vault_status')
    op.drop_index(op.f('ix_vault_status_program_id'), table_name='vault_status')
    op.drop_index(op.f('ix_vault_status_id'), table_name='vault_status')
    op.drop_table('vault_status')
    op.drop_index(op.f('ix_vault_ledger_user_id'), table_name='vault_ledger')
    op.drop_index(op.f('ix_vault_ledger_id'), table_name='vault_ledger')
    op.drop_table('vault_ledger')
    op.drop_index('uq_vault_earn_event_earn_event_id', table_name='vault_earn_event')
    op.drop_index('ix_vault_earn_event_user_created_at', table_name='vault_earn_event')
    op.drop_index(op.f('ix_vault_earn_event_id'), table_name='vault_earn_event')
    op.drop_table('vault_earn_event')
    op.drop_index(op.f('ix_user_xp_event_log_id'), table_name='user_xp_event_log')
    op.drop_table('user_xp_event_log')
    op.drop_table('user_segment')
    op.drop_table('user_retention_state')
    op.drop_index(op.f('ix_user_mission_progress_user_id'), table_name='user_mission_progress')
    op.drop_index(op.f('ix_user_mission_progress_reset_date'), table_name='user_mission_progress')
    op.drop_index(op.f('ix_user_mission_progress_mission_id'), table_name='user_mission_progress')
    op.drop_index(op.f('ix_user_mission_progress_id'), table_name='user_mission_progress')
    op.drop_table('user_mission_progress')
    op.drop_index(op.f('ix_user_level_reward_log_id'), table_name='user_level_reward_log')
    op.drop_table('user_level_reward_log')
    op.drop_table('user_level_progress')
    op.drop_index(op.f('ix_user_inventory_ledger_user_id'), table_name='user_inventory_ledger')
    op.drop_index(op.f('ix_user_inventory_ledger_item_type'), table_name='user_inventory_ledger')
    op.drop_index(op.f('ix_user_inventory_ledger_id'), table_name='user_inventory_ledger')
    op.drop_table('user_inventory_ledger')
    op.drop_index(op.f('ix_user_inventory_item_user_id'), table_name='user_inventory_item')
    op.drop_index(op.f('ix_user_inventory_item_item_type'), table_name='user_inventory_item')
    op.drop_index(op.f('ix_user_inventory_item_id'), table_name='user_inventory_item')
    op.drop_table('user_inventory_item')
    op.drop_index(op.f('ix_user_identity_history_user_id'), table_name='user_identity_history')
    op.drop_table('user_identity_history')
    op.drop_index(op.f('ix_user_idempotency_key_user_id'), table_name='user_idempotency_key')
    op.drop_index(op.f('ix_user_idempotency_key_status'), table_name='user_idempotency_key')
    op.drop_index(op.f('ix_user_idempotency_key_scope'), table_name='user_idempotency_key')
    op.drop_index(op.f('ix_user_idempotency_key_id'), table_name='user_idempotency_key')
    op.drop_table('user_idempotency_key')
    op.drop_index(op.f('ix_user_game_wallet_ledger_user_id'), table_name='user_game_wallet_ledger')
    op.drop_index(op.f('ix_user_game_wallet_ledger_token_type'), table_name='user_game_wallet_ledger')
    op.drop_index(op.f('ix_user_game_wallet_ledger_id'), table_name='user_game_wallet_ledger')
    op.drop_index(op.f('ix_user_game_wallet_ledger_created_at'), table_name='user_game_wallet_ledger')
    op.drop_table('user_game_wallet_ledger')
    op.drop_index(op.f('ix_user_game_wallet_user_id'), table_name='user_game_wallet')
    op.drop_index(op.f('ix_user_game_wallet_token_type'), table_name='user_game_wallet')
    op.drop_index(op.f('ix_user_game_wallet_id'), table_name='user_game_wallet')
    op.drop_table('user_game_wallet')
    op.drop_index('ix_user_event_log_user_created_at', table_name='user_event_log')
    op.drop_index(op.f('ix_user_event_log_id'), table_name='user_event_log')
    op.drop_index('ix_user_event_log_event_name', table_name='user_event_log')
    op.drop_table('user_event_log')
    op.drop_index(op.f('ix_user_cash_ledger_user_id'), table_name='user_cash_ledger')
    op.drop_index(op.f('ix_user_cash_ledger_id'), table_name='user_cash_ledger')
    op.drop_table('user_cash_ledger')
    op.drop_index(op.f('ix_user_activity_event_user_id'), table_name='user_activity_event')
    op.drop_index('ix_user_activity_event_user_created', table_name='user_activity_event')
    op.drop_index(op.f('ix_user_activity_event_id'), table_name='user_activity_event')
    op.drop_table('user_activity_event')
    op.drop_index('ix_user_activity_user_updated_at', table_name='user_activity')
    op.drop_index(op.f('ix_user_activity_user_id'), table_name='user_activity')
    op.drop_index(op.f('ix_user_activity_id'), table_name='user_activity')
    op.drop_table('user_activity')
    op.drop_index(op.f('ix_trial_token_bucket_user_id'), table_name='trial_token_bucket')
    op.drop_index(op.f('ix_trial_token_bucket_id'), table_name='trial_token_bucket')
    op.drop_table('trial_token_bucket')
    op.drop_index(op.f('ix_telegram_link_code_user_id'), table_name='telegram_link_code')
    op.drop_index(op.f('ix_telegram_link_code_code'), table_name='telegram_link_code')
    op.drop_table('telegram_link_code')
    op.drop_index('idx_team_score_points', table_name='team_score')
    op.drop_table('team_score')
    op.drop_index('idx_team_member_team', table_name='team_member')
    op.drop_table('team_member')
    op.drop_index('idx_tel_user', table_name='team_event_log')
    op.drop_index('idx_tel_season_team', table_name='team_event_log')
    op.drop_table('team_event_log')
    op.drop_table('survey')
    op.drop_index(op.f('ix_season_pass_progress_id'), table_name='season_pass_progress')
    op.drop_table('season_pass_progress')
    op.drop_index(op.f('ix_season_pass_level_id'), table_name='season_pass_level')
    op.drop_table('season_pass_level')
    op.drop_index(op.f('ix_roulette_segment_id'), table_name='roulette_segment')
    op.drop_table('roulette_segment')
    op.drop_index(op.f('ix_retention_roi_log_user_id'), table_name='retention_roi_log')
    op.drop_index(op.f('ix_retention_roi_log_id'), table_name='retention_roi_log')
    op.drop_index(op.f('ix_retention_roi_log_created_at'), table_name='retention_roi_log')
    op.drop_table('retention_roi_log')
    op.drop_index(op.f('ix_ranking_daily_id'), table_name='ranking_daily')
    op.drop_table('ranking_daily')
    op.drop_index(op.f('ix_ops_plan_plan_date'), table_name='ops_plan')
    op.drop_index(op.f('ix_ops_plan_id'), table_name='ops_plan')
    op.drop_index(op.f('ix_ops_plan_campaign_id'), table_name='ops_plan')
    op.drop_table('ops_plan')
    op.drop_index(op.f('ix_ops_log_entry_timestamp'), table_name='ops_log_entry')
    op.drop_index(op.f('ix_ops_log_entry_target_id'), table_name='ops_log_entry')
    op.drop_index('ix_ops_log_entry_ref_id_unique', table_name='ops_log_entry')
    op.drop_index(op.f('ix_ops_log_entry_id'), table_name='ops_log_entry')
    op.drop_index('ix_ops_log_entry_daily_log_date', table_name='ops_log_entry')
    op.drop_table('ops_log_entry')
    op.drop_index(op.f('ix_lottery_prize_id'), table_name='lottery_prize')
    op.drop_table('lottery_prize')
    op.drop_index(op.f('ix_external_ranking_data_user_id'), table_name='external_ranking_data')
    op.drop_index(op.f('ix_external_ranking_data_id'), table_name='external_ranking_data')
    op.drop_table('external_ranking_data')
    op.drop_index(op.f('ix_external_ranking_daily_deposit_delta_user_id'), table_name='external_ranking_daily_deposit_delta')
    op.drop_index(op.f('ix_external_ranking_daily_deposit_delta_kst_date'), table_name='external_ranking_daily_deposit_delta')
    op.drop_index(op.f('ix_external_ranking_daily_deposit_delta_id'), table_name='external_ranking_daily_deposit_delta')
    op.drop_table('external_ranking_daily_deposit_delta')
    op.drop_index(op.f('ix_event_participation_log_user_id'), table_name='event_participation_log')
    op.drop_index(op.f('ix_event_participation_log_participated_at'), table_name='event_participation_log')
    op.drop_index(op.f('ix_event_participation_log_id'), table_name='event_participation_log')
    op.drop_index(op.f('ix_event_participation_log_event_type'), table_name='event_participation_log')
    op.drop_index(op.f('ix_event_participation_log_event_id'), table_name='event_participation_log')
    op.drop_table('event_participation_log')
    op.drop_index('ix_dice_log_user_created_at', table_name='dice_log')
    op.drop_index(op.f('ix_dice_log_id'), table_name='dice_log')
    op.drop_table('dice_log')
    op.drop_index(op.f('ix_admin_user_profile_telegram_id'), table_name='admin_user_profile')
    op.drop_index(op.f('ix_admin_user_profile_external_id'), table_name='admin_user_profile')
    op.drop_table('admin_user_profile')
    op.drop_index(op.f('ix_admin_message_inbox_user_id'), table_name='admin_message_inbox')
    op.drop_index(op.f('ix_admin_message_inbox_message_id'), table_name='admin_message_inbox')
    op.drop_index(op.f('ix_admin_message_inbox_id'), table_name='admin_message_inbox')
    op.drop_table('admin_message_inbox')
    op.drop_index(op.f('ix_vault_program_id'), table_name='vault_program')
    op.drop_table('vault_program')
    op.drop_index(op.f('ix_user_telegram_id'), table_name='user')
    op.drop_index(op.f('ix_user_nickname'), table_name='user')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_index(op.f('ix_user_created_at'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_team_season_id'), table_name='team_season')
    op.drop_index('idx_team_season_time', table_name='team_season')
    op.drop_index('idx_team_season_active', table_name='team_season')
    op.drop_table('team_season')
    op.drop_index(op.f('ix_team_id'), table_name='team')
    op.drop_table('team')
    op.drop_table('segment_rule')
    op.drop_index(op.f('ix_season_pass_config_start_date'), table_name='season_pass_config')
    op.drop_index(op.f('ix_season_pass_config_is_active'), table_name='season_pass_config')
    op.drop_index(op.f('ix_season_pass_config_id'), table_name='season_pass_config')
    op.drop_index(op.f('ix_season_pass_config_end_date'), table_name='season_pass_config')
    op.drop_table('season_pass_config')
    op.drop_index(op.f('ix_roulette_config_id'), table_name='roulette_config')
    op.drop_table('roulette_config')
    op.drop_index(op.f('ix_ops_daily_log_date'), table_name='ops_daily_log')
    op.drop_table('ops_daily_log')
    op.drop_index(op.f('ix_ops_campaign_id'), table_name='ops_campaign')
    op.drop_table('ops_campaign')
    op.drop_index(op.f('ix_mission_logic_key'), table_name='mission')
    op.drop_index(op.f('ix_mission_id'), table_name='mission')
    op.drop_index(op.f('ix_mission_category'), table_name='mission')
    op.drop_index(op.f('ix_mission_action_type'), table_name='mission')
    op.drop_table('mission')
    op.drop_index(op.f('ix_lottery_config_id'), table_name='lottery_config')
    op.drop_table('lottery_config')
    op.drop_index(op.f('ix_feature_schedule_id'), table_name='feature_schedule')
    op.drop_table('feature_schedule')
    op.drop_index(op.f('ix_feature_config_id'), table_name='feature_config')
    op.drop_table('feature_config')
    op.drop_index(op.f('ix_event_config_target_segment'), table_name='event_config')
    op.drop_index(op.f('ix_event_config_id'), table_name='event_config')
    op.drop_index(op.f('ix_event_config_event_type'), table_name='event_config')
    op.drop_table('event_config')
    op.drop_index(op.f('ix_dice_config_id'), table_name='dice_config')
    op.drop_table('dice_config')
    op.drop_index(op.f('ix_app_ui_config_id'), table_name='app_ui_config')
    op.drop_table('app_ui_config')
    op.drop_index(op.f('ix_admin_message_id'), table_name='admin_message')
    op.drop_table('admin_message')
    op.drop_index(op.f('ix_admin_audit_log_id'), table_name='admin_audit_log')
    op.drop_index(op.f('ix_admin_audit_log_admin_id'), table_name='admin_audit_log')
    op.drop_table('admin_audit_log')
    # ### end Alembic commands ###
