#!/bin/bash
mysql -u xmasuser -p2026 xmas_event -e "SELECT TABLE_NAME, COLUMN_NAME FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME LIKE 'v2_%' ORDER BY TABLE_NAME, ORDINAL_POSITION"
