"""add user streak

Revision ID: 20260106_0730_add_user_streak
Revises: f5a1c0d2e9b4
Create Date: 2026-01-06 07:30:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20260106_0730_add_user_streak'
down_revision = 'f5a1c0d2e9b4'
branch_labels = None
depends_on = None


def _has_column(table_name: str, column_name: str) -> bool:
    inspector = sa.inspect(op.get_bind())
    try:
        return any(col.get("name") == column_name for col in inspector.get_columns(table_name))
    except Exception:
        return False


def _has_index(table_name: str, index_name: str) -> bool:
    inspector = sa.inspect(op.get_bind())
    try:
        return any(ix.get("name") == index_name for ix in inspector.get_indexes(table_name))
    except Exception:
        return False


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    if not _has_column('user', 'login_streak'):
        op.add_column('user', sa.Column('login_streak', sa.Integer(), server_default='0', nullable=False))
    if not _has_column('user', 'last_streak_updated_at'):
        op.add_column('user', sa.Column('last_streak_updated_at', sa.DateTime(), nullable=True))

    idx_name = op.f('idx_user_login_streak')
    if not _has_index('user', idx_name) and not _has_index('user', 'idx_user_login_streak'):
        op.create_index(idx_name, 'user', ['login_streak'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    idx_name = op.f('idx_user_login_streak')
    if _has_index('user', idx_name):
        op.drop_index(idx_name, table_name='user')
    elif _has_index('user', 'idx_user_login_streak'):
        op.drop_index('idx_user_login_streak', table_name='user')

    if _has_column('user', 'last_streak_updated_at'):
        op.drop_column('user', 'last_streak_updated_at')
    if _has_column('user', 'login_streak'):
        op.drop_column('user', 'login_streak')
    # ### end Alembic commands ###
